# Medical Examiner Case Archives

Cook County (Chicago) medical examiner records, taken from [here](https://datacatalog.cookcountyil.gov/Public-Safety/Medical-Examiner-Case-Archive/cjeq-bs86) after discovery via [Data is Plural](https://tinyletter.com/data-is-plural).

## Do your importing/setup

In [111]:
import pandas as pd
import numpy as np 
%matplotlib inline

## Read in the data, check its row count and column types

In [127]:
df = pd.read_csv("Medical_Examiner_Case_Archive.csv", na_values = "Data missing", names = ['Case_Number','Date_of_Incident','Date of Death', 'Age', 'Gender', 'Race', 'Latino', 'Manner_of_Death', 'Primary_Cause','Primary_Cause_Line_B','Primary_Cause_Line_C','Secondary_Cause','Gun_Related', 'Opioid_Related','Incident_Address','Incident_City','longitude','latitude','OBJECTID','location'])

In [128]:
df.shape

(22635, 20)

In [129]:
df.dtypes

Case_Number             object
Date_of_Incident        object
Date of Death           object
Age                     object
Gender                  object
Race                    object
Latino                  object
Manner_of_Death         object
Primary_Cause           object
Primary_Cause_Line_B    object
Primary_Cause_Line_C    object
Secondary_Cause         object
Gun_Related             object
Opioid_Related          object
Incident_Address        object
Incident_City           object
longitude               object
latitude                object
OBJECTID                object
location                object
dtype: object

## Cleaning up your data

First you'll want to convert the `Race` and `Gender` columns from codes into actual text to make analysis easier.

### Gender codes

* `-1` - `Data missing`
* `0` - `Female`
* `1` - `Male`
* `2` - `Unknown`

### Race codes

* `-1` - `Data missing`
* `0` - `American Indian`
* `1` - `Asian`
* `2` - `Black`
* `3` - `Other`
* `4` - `Unknown`
* `5` - `White`

In [130]:
#Isn't it kind of text already? :|

## What percent of the dataset is men, and what percent is women?

It should display as **Male** and **Female**, not as numbers.

In [131]:
df[df.Gender == "Male"].Gender.value_counts()

Male    16158
Name: Gender, dtype: int64

In [132]:
men_perc = 16158

In [133]:
df[df.Gender == "Female"].Gender.value_counts()

Female    6363
Name: Gender, dtype: int64

In [134]:
df[df.Gender == "Unknown"].Gender.value_counts()

Unknown    12
Name: Gender, dtype: int64

In [135]:
clean_total = 22634 - 12 
clean_total

22622

In [136]:
men_perc = 16158 * 100 / 22622
round(men_perc, 2)

71.43

In [137]:
women_perc = 6363 * 100 / 22622
round(women_perc,2)

28.13

## Getting rid of "Data missing"

`Unknown` means that officially the gender or race is unknown, while `Data missing` means the record is incomplete. That means "Data missing" should have been `NaN`!

Go back to your `read_csv` many cells before and make it so that "Data missing" is automatically set as `NaN`.

- *Tip: Do not use `.replace` for this one!*
- *Tip: Look at the options for `read_csv`, there's something that lets you specify missing values*
- *Tip: It isn't `"Data missing"` - think about how you already replaced*
- *Tip: Be sure you're using an array when you tell it what the 'missing' options are*

### After you've done this, re-run all of the the previous cells and confirm that `"Data missing"` does not exist any more

In [244]:
df

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
0,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
1,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,20468,NaN
2,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,2110 W. 21ST PL #1,CHICAGO,-87.6788449,41.8532787,77827,"(41.8532787, -87.6788449)"
3,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
4,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64,Female,White,false,NaN,NaN,NaN,NaN,NaN,False,False,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.7281769,41.9574677,77823,"(41.9574677, -87.7281769)"
5,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,3947 W. LEXINGTON STREET,CHICAGO,-87.7247386,41.8714515,77822,"(41.8714515, -87.7247386)"
6,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28,Male,Black,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,77903,NaN
7,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55,Male,White,false,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,true,False,209 E. LAKE SHORE DRIVE,CHICAGO,-87.6214206,41.900571,77930,"(41.900571, -87.6214206)"
8,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
9,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
10,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,910 W 76TH 3RD FLOOR,CHICAGO,-87.6470422,41.7561236,78337,"(41.7561236, -87.6470422)"
11,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55,Male,Black,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,"300 NORTH STATE, APT 6021",CHICAGO,-87.6290778,41.8879298,78480,"(41.8879298, -87.6290778)"
12,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
13,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
14,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47,Male,Black,false,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,False,False,1132 TROOST AVENUE APT 101,FOREST PARK,-87.8169297,41.8653484,77748,"(41.8653484, -87.8169297)"
15,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37,Male,White,true,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,159TH AND FINCH,HARVEY,-87.6401039,41.6008977,58723,"(41.6008977, -87.6401039)"
16,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,False,true,6547 W. 111TH APT W-27,WORTH,-87.7817317,41.6896403,63784,"(41.6896403, -87.7817317)"
17,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31,Male,Black,false,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,False,False,6916 S. MICHIGAN AVENUE,CHICAGO,-87.6221153,41.7686918,77583,"(41.7686918, -87.6221153)"
18,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66,Male,White,false,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,False,False,6238 w. 26th #205,BERWYN,-87.7800927,41.8432672,57453,"(41.8432672, -87.7800927)"
19,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
20,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31,Male,Black,false,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,4811 W. WASHINGTON BLVD.,CHICAGO,-87.7456512,41.8817674,77825,"(41.8817674, -87.7456512)"
21,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69,Male,White,false,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,False,False,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
22,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1653 W Congress Pkwy,NaN,-87.6679448,41.8751081,78013,"(41.8751081, -87.6679448)"
23,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37,Male,Black,false,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,False,False,1440 EMBASSY LANE,FORD HEIGHTS,-87.5852155,41.5133297,78840,"(41.5133297, -87.5852155)"
24,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39,Female,Black,false,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
25,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54,Male,White,false,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,False,False,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
26,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
27,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,1815 N. KARLOV,CHICAGO,-87.7286374,41.9140656,77857,"(41.9140656, -87.7286374)"
28,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48,Male,White,false,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,False,False,2631 West Rascher Avenue,CHICAGO,-87.6954789,41.9802154,77843,"(41.9802154, -87.6954789)"
29,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76,Male,White,false,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,False,False,8108 ODELL AVENUE,BRIDGEVIEW,-87.8036075,41.7440145,77849,"(41.7440145, -87.8036075)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22605,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50,Male,White,true,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",False,False,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.6967797,41.8521269,70244,"(41.8521269, -87.6967797)"
22606,ME2018-02089,05/01/2018 08:16:00 PM,01/01/1970 12:00:00 AM,NaN,NaN,NaN,false,NaN,NON-HUMAN REMAINS,NaN,NaN,NaN,False,False,729 E OAKWOOD BLVD,CHICAGO,-87.608927,41.8226731,75628,"(41.8226731, -87.608927)"
22607,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48,Female,Black,false,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,False,False,201 W. 69TH STREET,CHICAGO,-87.6302482,41.768766,72642,"(41.768766, -87.6302482)"
22608,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,7846 S Kingston,CHICAGO,-87.5626855,41.7522303,77795,"(41.7522303, -87.5626855)"
22609,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.6228345,41.8417184,77971,"(41.8417184, -87.6228345)"
22610,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,250 N. Western Avenue,NaN,-87.6869702,41.8860494,77976,"(41.8860494, -87.6869702)"
22611,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56,Male,Black,false,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,False,False,216 w. 147TH STREET,HARVEY,-87.6689548,41.6224931,78086,"(41.6224931, -87.6689548)"
22612,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,False,False,1755 HENLEY ST #2N,GLENVIEW,-87.8022124,42.0700695,78280,"(42.0700695, -87.8022124)"
22613,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.8624014,78381,"(41.8624014, -87.640188)"
22614,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9858 IRVING PARK ROAD,SCHILLER PARK,-87.8733682,41.9561261,78475,"(41.9561261, -87.8733682)"
22615,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,2373 E 70TH ST,CHICAGO,-87.5672724,41.768022,78635,"(41.768022, -87.5672724)"
22616,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,9558 SHERMER ROAD,MORTON GROVE,-87.8117716,42.0547758,77791,"(42.0547758, -87.8117716)"
22617,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22618,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.0181695,77811,"(42.0181695, -87.982034)"
22619,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.6570785,41.7267165,77789,"(41.7267165, -87.6570785)"
22620,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2058 W. Hutchinson,CHICAGO,-87.6812383,41.9589732,67932,"(41.9589732, -87.6812383)"
22621,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.6652684,41.7637034,59566,"(41.7637034, -87.6652684)"
22622,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9000 West College Park way,PALOS HILLS,-87.837735,41.6895094,77788,"(41.6895094, -87.837735)"
22623,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60,Female,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,8419 S ESCANABA AVE,NaN,-87.5536891,41.7422211,67087,"(41.7422211, -87.5536891)"
22624,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1512 SILVER LANE APT #1,PALATINE,-88.0073415,42.1364923,77779,"(42.1364923, -88.0073415)"
22625,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1127 Miller Lane;,BUFFALO GROVE,-87.9784066,42.1347284,77891,"(42.1347284, -87.9784066)"
22626,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.6438762,41.9419529,77939,"(41.9419529, -87.6438762)"
22627,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,16102 RICHMOND AVE,MARKHAM,-87.687286,41.5972276,78018,"(41.5972276, -87.687286)"
22628,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9158 S. HARVARD AVENUE,CHICAGO,-87.6321484,41.7277694,77985,"(41.7277694, -87.6321484)"
22629,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42,Male,Black,false,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,true,False,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.5839097,41.7464877,78103,"(41.7464877, -87.5839097)"
22630,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.6934761,41.9824976,78129,"(41.9824976, -87.6934761)"
22631,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",False,False,16416 EVANS AVENUE,SOUTH HOLLAND,-87.6009945,41.5966344,78272,"(41.5966344, -87.6009945)"
22632,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68,Male,Am. Indian,false,PENDING,PENDING,NaN,NaN,NaN,False,False,15243 3RD AVE.,PHOENIX,-87.6318491,41.6119409,78496,"(41.6119409, -87.6318491)"
22633,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50,Male,White,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.07934,42.0394902,78745,"(42.0394902, -88.07934)"
22634,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,False,3914 212 PL,MATTESON,-87.7114567,41.5041136,78828,"(41.5041136, -87.7114567)"

## What is the most common race in the dataset? We want percentages.

We'll come back to this later, I'm just having you check the column for now.

In [139]:
df.Race.value_counts()

White         12490
Black          9366
Asian           342
Other           269
Unknown          28
Am. Indian       15
Race              1
Name: Race, dtype: int64

In [140]:
cleaned_total = 22634 - 28 
cleaned_total

22606

In [141]:
white_perc = 12490 *100 / 22606
round(white_perc, 2)

55.25

## Do a `.value_counts()` on the `Opioid Related` column

In [142]:
df["Opioid_Related"].value_counts()

true              3378
Opioid Related       1
Name: Opioid_Related, dtype: int64

## That's weird. Did everyone die from opioids? Try again, but including missing data.

In [143]:
df["Opioid_Related"].value_counts()

true              3378
Opioid Related       1
Name: Opioid_Related, dtype: int64

## Cleaning up True/False columns

For some reason in this dataset, the True/False columns are either `True` or `NaN`. `NaN` causes a lot of problems, I'd rather have it be false.

You can use [`fillna`](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.fillna.html) to fill in empty data - it's like `.replace` but for `NaN`.

### Replace all `NaN` values with `False` for the "Gun Related" and "Opioid Related" columns.

In [144]:
df["Gun_Related"] = df["Gun_Related"].fillna(False)

In [145]:
df["Opioid_Related"] = df["Opioid_Related"].fillna(False)

### Do another value counts on Opioid Related to make sure it has both True and False values

In [146]:
df["Opioid_Related"].value_counts()

False             19256
true               3378
Opioid Related        1
Name: Opioid_Related, dtype: int64

# Back to analysis!

## What's the average age people were when they died?

In [149]:
#df["Age"] = df.Age.astype(float)
#round(df.Age.mean())
df['Age'].astype(str).astype(int)

ValueError: invalid literal for int() with base 10: 'Age'

## Let's look at how the oldest people died

We're just going to browse. Read through how the **oldest 30 people died.**

In [46]:
df.Primary_Cause.sort_values(ascending=False).head(30)

5211                         ZOLPIDEM AND ETHANOL TOXICITY
17805                                   WITNESSED DROWNING
12342                      VOLVULUS OF THE SMALL INTESTINE
17881                                  VITIATED ATMOSPHERE
8492                                      VIRAL MENINGITIS
8195                                      VIRAL MENINGITIS
6637     VENOUS THROMBOEMBOLISM ASSOCIATED WITH METASTA...
6300                       VALVULAR INFECTIVE ENDOCARDITIS
14708                               VALVULAR HEART DISEASE
9080                                VALVULAR HEART DISEASE
13831                               VALVULAR HEART DISEASE
18887                               VALVULAR HEART DISEASE
18061                      VALVULAR CARDIOVASCULAR DISEASE
8883                       VALVULAR CARDIOVASCULAR DISEASE
19523                      VALVULAR CARDIOVASCULAR DISEASE
17333                      VALVULAR CARDIOVASCULAR DISEASE
16231                             VALVULAR CARDIAC DISEASE
4766                                             UROSEPSIS
15128    UPPER GASTROINTESTINAL HEMORRHAGE OF UNKNOWN E...
15956                    UPPER GASTROINTESTINAL HEMORRHAGE
19782                    UPPER GASTROINTESTINAL HEMORRHAGE
1180                     UPPER GASTROINTESTINAL HEMORRHAGE
21650                    UPPER GASTROINTESTINAL HEMORRHAGE
13093                    UPPER GASTROINTESTINAL HEMORRHAGE
8305                     UPPER GASTROINTESTINAL HEMORRHAGE
8750                     UPPER GASTROINTESTINAL HEMORRHAGE
8723                     UPPER GASTROINTESTINAL HEMORRHAGE
14157                    UPPER GASTROINTESTINAL HEMORRHAGE
2432                     UPPER GASTROINTESTINAL HEMORRHAGE
11438                    UPPER GASTROINTESTINAL HEMORRHAGE
Name: Primary_Cause, dtype: object

## Seems like a lot of problems with fractures

### What's the median age of someone dying from a cause that involves a fracture?

Are fractures especially dangerous for the elderly?

- *Tip: Filter for a cause that involves a fracture, then take the median age*
- *Tip: If you get a "cannot index NA values" error, the problem is it's trying to search `NaN` values and doesn't know what to do with them. You need to tell pandas to count `NaN` as false by setting another option - it isn't `NaN=False`, but it's close!*

In [147]:
df[df["Primary Cause"].str.contains("INJURIES").fillna(False)].Age.median()

KeyError: 'Primary Cause'

### What's the median age of each manner of death?

It looks like different kinds of death might happen to different ages of people. Let's investigate that further.

In [48]:
round(df.Age.median())

TypeError: could not convert string to float: 'Age'

### Who is the oldest homicide victim?

It looks like homicide is for young people, so maybe we'll find an interesting outlier?

In [49]:
df[df["Manner_of_Death"] == "HOMICIDE"].Age.sort_values(ascending=False).head(1)

3703    98
Name: Age, dtype: object

## Investigating toxicity-related homicides

She was old, and was purposefully overdosed on morphine and hydrocodone. Might have been euthenasia? Let's find similar cases.

### Find every homicide where the primary cause of death is some sort of toxicity

Toxicity can just overdose. You should have **ten rows**.

- *Tip: If you're doing this as one statement, make sure you use your parentheses correctly. If you leave them out, you'll have zero rows*
- *Tip: You could make a homicides-only dataframe if you wanted to*

In [50]:
df[df["Manner_of_Death"] == "HOMICIDE"]["Primary_Cause"].str.contains("TOXICITY", np.nan).value_counts()

False    2829
True       10
Name: Primary_Cause, dtype: int64

In [51]:
df

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
0,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
1,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,20468,NaN
2,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,2110 W. 21ST PL #1,CHICAGO,-87.6788449,41.8532787,77827,"(41.8532787, -87.6788449)"
3,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
4,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64,Female,White,false,NaN,NaN,NaN,NaN,NaN,False,False,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.7281769,41.9574677,77823,"(41.9574677, -87.7281769)"
5,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,3947 W. LEXINGTON STREET,CHICAGO,-87.7247386,41.8714515,77822,"(41.8714515, -87.7247386)"
6,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28,Male,Black,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,77903,NaN
7,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55,Male,White,false,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,true,False,209 E. LAKE SHORE DRIVE,CHICAGO,-87.6214206,41.900571,77930,"(41.900571, -87.6214206)"
8,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
9,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
10,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,910 W 76TH 3RD FLOOR,CHICAGO,-87.6470422,41.7561236,78337,"(41.7561236, -87.6470422)"
11,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55,Male,Black,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,"300 NORTH STATE, APT 6021",CHICAGO,-87.6290778,41.8879298,78480,"(41.8879298, -87.6290778)"
12,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
13,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
14,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47,Male,Black,false,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,False,False,1132 TROOST AVENUE APT 101,FOREST PARK,-87.8169297,41.8653484,77748,"(41.8653484, -87.8169297)"
15,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37,Male,White,true,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,159TH AND FINCH,HARVEY,-87.6401039,41.6008977,58723,"(41.6008977, -87.6401039)"
16,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,False,true,6547 W. 111TH APT W-27,WORTH,-87.7817317,41.6896403,63784,"(41.6896403, -87.7817317)"
17,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31,Male,Black,false,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,False,False,6916 S. MICHIGAN AVENUE,CHICAGO,-87.6221153,41.7686918,77583,"(41.7686918, -87.6221153)"
18,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66,Male,White,false,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,False,False,6238 w. 26th #205,BERWYN,-87.7800927,41.8432672,57453,"(41.8432672, -87.7800927)"
19,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
20,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31,Male,Black,false,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,4811 W. WASHINGTON BLVD.,CHICAGO,-87.7456512,41.8817674,77825,"(41.8817674, -87.7456512)"
21,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69,Male,White,false,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,False,False,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
22,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1653 W Congress Pkwy,NaN,-87.6679448,41.8751081,78013,"(41.8751081, -87.6679448)"
23,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37,Male,Black,false,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,False,False,1440 EMBASSY LANE,FORD HEIGHTS,-87.5852155,41.5133297,78840,"(41.5133297, -87.5852155)"
24,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39,Female,Black,false,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
25,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54,Male,White,false,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,False,False,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
26,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
27,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,1815 N. KARLOV,CHICAGO,-87.7286374,41.9140656,77857,"(41.9140656, -87.7286374)"
28,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48,Male,White,false,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,False,False,2631 West Rascher Avenue,CHICAGO,-87.6954789,41.9802154,77843,"(41.9802154, -87.6954789)"
29,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76,Male,White,false,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,False,False,8108 ODELL AVENUE,BRIDGEVIEW,-87.8036075,41.7440145,77849,"(41.7440145, -87.8036075)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22605,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50,Male,White,true,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",False,False,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.6967797,41.8521269,70244,"(41.8521269, -87.6967797)"
22606,ME2018-02089,05/01/2018 08:16:00 PM,01/01/1970 12:00:00 AM,NaN,NaN,NaN,false,NaN,NON-HUMAN REMAINS,NaN,NaN,NaN,False,False,729 E OAKWOOD BLVD,CHICAGO,-87.608927,41.8226731,75628,"(41.8226731, -87.608927)"
22607,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48,Female,Black,false,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,False,False,201 W. 69TH STREET,CHICAGO,-87.6302482,41.768766,72642,"(41.768766, -87.6302482)"
22608,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,7846 S Kingston,CHICAGO,-87.5626855,41.7522303,77795,"(41.7522303, -87.5626855)"
22609,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.6228345,41.8417184,77971,"(41.8417184, -87.6228345)"
22610,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,250 N. Western Avenue,NaN,-87.6869702,41.8860494,77976,"(41.8860494, -87.6869702)"
22611,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56,Male,Black,false,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,False,False,216 w. 147TH STREET,HARVEY,-87.6689548,41.6224931,78086,"(41.6224931, -87.6689548)"
22612,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,False,False,1755 HENLEY ST #2N,GLENVIEW,-87.8022124,42.0700695,78280,"(42.0700695, -87.8022124)"
22613,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.8624014,78381,"(41.8624014, -87.640188)"
22614,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9858 IRVING PARK ROAD,SCHILLER PARK,-87.8733682,41.9561261,78475,"(41.9561261, -87.8733682)"
22615,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,2373 E 70TH ST,CHICAGO,-87.5672724,41.768022,78635,"(41.768022, -87.5672724)"
22616,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,9558 SHERMER ROAD,MORTON GROVE,-87.8117716,42.0547758,77791,"(42.0547758, -87.8117716)"
22617,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22618,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.0181695,77811,"(42.0181695, -87.982034)"
22619,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.6570785,41.7267165,77789,"(41.7267165, -87.6570785)"
22620,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2058 W. Hutchinson,CHICAGO,-87.6812383,41.9589732,67932,"(41.9589732, -87.6812383)"
22621,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.6652684,41.7637034,59566,"(41.7637034, -87.6652684)"
22622,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9000 West College Park way,PALOS HILLS,-87.837735,41.6895094,77788,"(41.6895094, -87.837735)"
22623,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60,Female,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,8419 S ESCANABA AVE,NaN,-87.5536891,41.7422211,67087,"(41.7422211, -87.5536891)"
22624,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1512 SILVER LANE APT #1,PALATINE,-88.0073415,42.1364923,77779,"(42.1364923, -88.0073415)"
22625,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1127 Miller Lane;,BUFFALO GROVE,-87.9784066,42.1347284,77891,"(42.1347284, -87.9784066)"
22626,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.6438762,41.9419529,77939,"(41.9419529, -87.6438762)"
22627,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,16102 RICHMOND AVE,MARKHAM,-87.687286,41.5972276,78018,"(41.5972276, -87.687286)"
22628,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9158 S. HARVARD AVENUE,CHICAGO,-87.6321484,41.7277694,77985,"(41.7277694, -87.6321484)"
22629,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42,Male,Black,false,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,true,False,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.5839097,41.7464877,78103,"(41.7464877, -87.5839097)"
22630,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.6934761,41.9824976,78129,"(41.9824976, -87.6934761)"
22631,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",False,False,16416 EVANS AVENUE,SOUTH HOLLAND,-87.6009945,41.5966344,78272,"(41.5966344, -87.6009945)"
22632,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68,Male,Am. Indian,false,PENDING,PENDING,NaN,NaN,NaN,False,False,15243 3RD AVE.,PHOENIX,-87.6318491,41.6119409,78496,"(41.6119409, -87.6318491)"
22633,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50,Male,White,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.07934,42.0394902,78745,"(42.0394902, -88.07934)"
22634,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,False,3914 212 PL,MATTESON,-87.7114567,41.5041136,78828,"(41.5041136, -87.7114567)"

### Okay, nope, we were wrong.

Those were almost **all from fires**. Apparently homicide is not the best place to go looking for toxicity. What's the most popular manner of death for primary causes involving toxicity?

- *Tip: Remember that `['colname']` is the same as `.colname`. You can't do `.col with spaces` so you'll need to do `['col with spaces']` a lot in this dataset
- *Tip: Or I guess if you really wanted to, you could rename your columns to have spaces in them (IF YOU DO THIS DON'T DO IT IN EXCEL BECAUSE IT WILL PROBABLY BREAK YOUR CSV.)*

In [52]:
df[df["Primary_Cause"].str.contains("TOXICITY").fillna(False)]

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
16,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,False,true,6547 W. 111TH APT W-27,WORTH,-87.7817317,41.6896403,63784,"(41.6896403, -87.7817317)"
46,ME2018-00910,02/19/2018 08:00:00 PM,02/19/2018 08:22:00 PM,56,Male,Black,false,ACCIDENT,COMBINED DRUG (COCAINE AND HEROIN) TOXICITY,NaN,NaN,NaN,False,true,7724 SOUTH LOOMIS BLVD #1,CHICAGO,-87.6589318,41.7532818,69589,"(41.7532818, -87.6589318)"
52,ME2018-00400,01/20/2018 11:15:00 AM,01/20/2018 11:57:00 AM,19,Male,White,false,ACCIDENT,HEROIN TOXICITY,NaN,NaN,NaN,False,true,"5719 S. Kimbark, Apt. 3",CHICAGO,-87.5941419,41.7907435,77880,"(41.7907435, -87.5941419)"
54,ME2018-00643,02/03/2018 10:45:00 AM,02/03/2018 11:11:00 AM,35,Male,White,false,ACCIDENT,"ETHANOL AND COMBINED DRUG (PROBABLE HEROIN, CY...",NaN,NaN,NaN,False,true,"2540 N. Manheim Road, Rm#215",FRANKLIN PARK,NaN,NaN,77879,NaN
55,ME2018-00671,02/05/2018 12:00:00 AM,02/05/2018 12:10:00 AM,27,Male,White,false,ACCIDENT,COMBINED FENTANYL AND PROBABLE HEROIN TOXICITY,NaN,NaN,OBESITY,False,true,3435 W. VAN BUREN,CHICAGO,-87.7119935,41.8753913,77910,"(41.8753913, -87.7119935)"
66,ME2018-01129,03/03/2018 03:45:00 AM,03/03/2018 04:31:00 AM,34,Male,Black,false,ACCIDENT,ACUTE ETHANOL TOXICITY,NaN,NaN,NaN,False,False,7899 SOUTH SHORE,CHICAGO,-87.5481134,41.7520559,68080,"(41.7520559, -87.5481134)"
70,ME2018-01356,03/15/2018 01:31:00 PM,03/15/2018 01:44:00 PM,26,Male,White,false,ACCIDENT,"FENTANYL, HEROIN, AND ALPRAZOLAM TOXICITY",NaN,NaN,NaN,False,true,710 N. 4TH AVENUE,MAYWOOD,-87.8385636,41.8939818,77870,"(41.8939818, -87.8385636)"
91,ME2017-05713,12/07/2017 09:00:00 AM,12/07/2017 09:33:00 AM,43,Male,White,false,SUICIDE,"COMBINED ALPRAZOLAM, HYDROCODONE, ACETAMINOPHE...",NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,true,"920 Ridge Square, Unit 209",ELK GROVE VILLAGE,-87.9895624,42.0033733,59870,"(42.0033733, -87.9895624)"
94,ME2018-01560,03/29/2018 06:50:00 PM,03/29/2018 07:12:00 PM,38,Male,Asian,false,ACCIDENT,COCAINE AND FENTANYL TOXICITY,NaN,NaN,NaN,False,true,535 N MICHIGAN AVE #2705,CHICAGO,-87.6235405,41.8919752,66297,"(41.8919752, -87.6235405)"
100,ME2018-01570,03/30/2018 03:33:00 PM,03/30/2018 04:20:00 PM,50,Male,White,false,ACCIDENT,"COCAINE, FENTANYL AND ACETYL FENTANYL TOXICITY",NaN,NaN,NaN,False,true,1042 N. KNOLLWOOD DR. UNIT A,SCHAUMBURG,-88.1382195,42.0445787,62417,"(42.0445787, -88.1382195)"
103,ME2018-01574,03/30/2018 10:43:00 PM,03/30/2018 11:03:00 PM,40,Female,White,false,ACCIDENT,"COMBINED DRUG (FENTANYL, METHADONE, AND ALPRAZ...",NaN,NaN,NaN,False,true,4345 AUTHUR AVE.,BROOKFIELD,NaN,NaN,63618,NaN
107,ME2018-01103,03/01/2018 02:02:00 PM,03/01/2018 02:45:00 PM,68,Male,Black,false,ACCIDENT,COMBINED DRUG (FENTANYL AND METHADONE) TOXICITY,NaN,NaN,NaN,False,true,1541 SOUTH HAMLIN,CHICAGO,-87.7198186,41.8595195,78255,"(41.8595195, -87.7198186)"
108,ME2018-02197,05/07/2018 09:27:00 AM,05/08/2018 05:23:00 AM,38,Female,White,false,ACCIDENT,FENTANYL AND COCAINE TOXICITY,NaN,NaN,NaN,False,true,15611 DIXIE HWY (APT 2),HARVEY,-87.6693327,41.6057103,78760,"(41.6057103, -87.6693327)"
109,ME2017-05182,11/04/2017 08:45:00 PM,11/04/2017 09:03:00 PM,50,Male,Black,false,ACCIDENT,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,False,true,5319 S. WALCOTT,CHICAGO,-87.6717184,41.7970338,77967,"(41.7970338, -87.6717184)"
110,ME2017-05643,12/02/2017 02:50:00 PM,12/02/2017 02:44:00 PM,45,Male,White,false,ACCIDENT,"COMBINED DRUG (HEROIN, FENTANYL, AND ACETYL FE...",NaN,NaN,NaN,False,true,4023 West Congress Parkway,CHICAGO,-87.7263732,41.8742991,77943,"(41.8742991, -87.7263732)"
129,ME2018-02201,04/10/2018 01:14:00 AM,04/14/2018 09:20:00 PM,57,Female,White,false,ACCIDENT,COMBINED DRUG (BENZODIAZEPINE AND PROBABLE HER...,NaN,NaN,NaN,False,true,411 FOREST PRESERVE DRIVE.,WOOD DALE,NaN,NaN,78485,NaN
162,ME2018-02220,05/02/2018 12:00:00 PM,05/05/2018 03:17:00 PM,35,Female,White,false,ACCIDENT,COMPLICATIONS OF METHADONE TOXICITY,NaN,NaN,NaN,False,true,15715 INDEPENDENCE CT,OAK FOREST,-87.7574509,41.6059968,78072,"(41.6059968, -87.7574509)"
176,ME2018-00926,02/20/2018 12:00:00 PM,02/20/2018 12:36:00 PM,39,Male,White,true,ACCIDENT,COMBINED HEROIN AND FENTANYL TOXICITY,NaN,NaN,NaN,False,true,4345 SOUTH PACKERS,NaN,-87.6576873,41.8147004,78047,"(41.8147004, -87.6576873)"
194,ME2017-04357,09/16/2017 03:46:00 AM,09/16/2017 04:01:00 AM,66,Male,White,false,ACCIDENT,FENTANYL AND ACETYL FENTANYL TOXICITY,NaN,NaN,NaN,False,true,7835 WEST CRESSETT,ELMWOOD PARK,-87.8224024,41.9301994,78115,"(41.9301994, -87.8224024)"
229,ME2016-03209,06/30/2016 09:45:00 AM,06/30/2016 10:02:00 AM,57,Male,White,false,ACCIDENT,ACUTE OXYCODONE AND OXYMORPHONE TOXICITY,NaN,NaN,NaN,False,true,7101 Emerson Street,MORTON GROVE,-87.8036954,42.0517323,60635,"(42.0517323, -87.8036954)"
233,ME2018-01362,03/16/2018 01:53:00 AM,03/16/2018 02:06:00 AM,49,Male,White,false,ACCIDENT,"COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TO...",NaN,NaN,NaN,False,true,945 W. BELMONT AVE.,CHICAGO,-87.6532951,41.9398725,78209,"(41.9398725, -87.6532951)"
234,ME2018-01822,04/15/2018 09:00:00 AM,04/15/2018 09:21:00 AM,57,Male,White,false,ACCIDENT,"ALCOHOL, TEMAZEPAM AND ALPRAZOLAM TOXICITY",NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,252 W. JENNIFER LANE #1,PALATINE,-88.0498716,42.1246964,78220,"(42.1246964, -88.0498716)"
244,ME2018-02302,05/10/2018 05:00:00 PM,05/14/2018 02:50:00 PM,61,Female,White,false,ACCIDENT,COMPLICATIONS OF OPIATE AND BENZODIAZEPINE TOX...,NaN,NaN,"DIABETES MELLITUS, HYPERTENSIVE CARDIOVASCULAR...",False,true,3036 W. BELMONT,CHICAGO,-87.7042375,41.9395819,78349,"(41.9395819, -87.7042375)"
253,ME2017-00383,01/22/2017 09:30:00 AM,01/22/2017 10:00:00 AM,53,Female,White,false,ACCIDENT,"ETHANOL AND COMBINED DRUG (HYDROCODONE, LEVETI...",NaN,NaN,NaN,False,true,2519 NORTH ROCKWELL STREET,CHICAGO,-87.6923633,41.9272948,74629,"(41.9272948, -87.6923633)"
256,ME2017-06107,12/27/2017 06:18:00 AM,12/30/2017 07:28:00 AM,27,Male,White,false,ACCIDENT,"FENTANYL, DIAZEPAM, LORAZEPAM, AND SERTRALINE ...",NaN,NaN,HYPOTHERMIA DUE TO COLD EXPOSURE,False,true,135 E OAK ST,CHICAGO,-87.6246305,41.9007545,78228,"(41.9007545, -87.6246305)"
354,ME2018-02380,05/20/2018 09:25:00 AM,05/20/2018 10:03:00 AM,40,Male,Black,false,ACCIDENT,ETHANOL TOXICITY,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC E...",False,False,6803 S. Clyde,CHICAGO,-87.5739333,41.7715777,78574,"(41.7715777, -87.5739333)"
357,ME2018-00475,01/23/2018 09:42:00 PM,01/23/2018 09:59:00 PM,53,Female,Black,false,ACCIDENT,COCAINE TOXICITY,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,14134 PAGE ST.,DIXMOOR,-87.6598032,41.6322383,58259,"(41.6322383, -87.6598032)"
389,ME2018-01138,03/03/2018 09:30:00 AM,03/03/2018 10:13:00 AM,27,Male,Black,false,ACCIDENT,FENTANYL AND ALPRAZOLAM TOXICITY,NaN,NaN,NaN,False,true,7829 S. PEORIA 2ND FLOOR APT,CHICAGO,-87.6462021,41.7515321,68896,"(41.7515321, -87.6462021)"
397,ME2018-01232,03/08/2018 02:10:00 PM,03/08/2018 02:42:00 PM,36,Male,White,true,ACCIDENT,"COMBINED DRUG (CARFENTANIL, FURANYL FENTANYL, ...",NaN,NaN,NaN,False,true,1600 N. WESTERN AND NORTH AVE.,CHICAGO,-87.6873004,41.9103425,69942,"(41.9103425, -87.6873004)"
399,ME2018-01248,03/09/2018 12:00:00 AM,03/09/2018 11:41:00 AM,45,Female,Black,false,ACCIDENT,COCAINE TOXICITY,NaN,NaN,NaN,False,False,3554 W Ohio,CHICAGO,-87.7156869,41.8918636,69058,"(41.8918636, -87.7156869)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22348,ME2017-03770,08/13/2017 12:30:00 PM,08/14/2017 12:10:00 AM,51,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, OPIATE, AND FENTANYL) ...",NaN,NaN,NaN,False,true,4500 W. CHICAGO AVE.,CHICAGO,-87.738492,41.8952018,76342,"(41.8952018, -87.738492)"
22353,ME2017-04237,09/09/2017 10:30:00 PM,09/09/2017 10:40:00 PM,25,Male,White,false,ACCIDENT,"COMBINED DRUG (PSEUDOEPHEDRINE, ALPRAZOLAM, HY...",NaN,NaN,NaN,False,true,1826 W. EVERGREEN AVE APT #1,CHICAGO,-87.6745324,41.9073189,68991,"(41.9073189, -87.6745324)"
22370,ME2017-04789,09/06/2017 12:00:00 PM,10/10/2017 02:41:00 PM,51,Female,White,false,ACCIDENT,"COMBINED DRUG (HYDROCODONE, ACETAMINOPHEN, BUT...",NaN,NaN,"PNEUMONIA, CHRONIC OBSTRUCTIVE PULMONARY DISEA...",False,true,7001 West Cullom Ave,NORRIDGE,-87.803138,41.9574595,59742,"(41.9574595, -87.803138)"
22372,ME2017-04861,10/15/2017 06:14:00 AM,10/15/2017 07:18:00 AM,30,Male,White,false,ACCIDENT,"COMBINED FENTANYL, ACETYL FENTANYL AND ETHANOL...",NaN,NaN,NaN,False,true,730 W. Cornelia Ave. Apt. 307,CHICAGO,-87.6483097,41.9457153,77345,"(41.9457153, -87.6483097)"
22375,ME2017-04909,10/18/2017 03:13:00 PM,10/19/2017 01:53:00 AM,34,Male,White,false,ACCIDENT,"COMBINED DRUG (FENTANYL, ACETYL FENTANYL, COCA...",NaN,NaN,NaN,False,true,14053 S. 85th Avenue,ORLAND PARK,-87.827464,41.6364756,59368,"(41.6364756, -87.827464)"
22378,ME2017-05090,10/29/2017 07:54:00 PM,10/29/2017 08:02:00 PM,33,Male,Black,false,ACCIDENT,COMBINED DRUG (DESPROPRIONYL FENTANYL(4-ANPP) ...,NaN,NaN,NaN,False,true,739 SUPERIOR,CALUMET CITY,-87.5441328,41.6131403,62818,"(41.6131403, -87.5441328)"
22381,ME2017-05220,11/05/2017 02:42:00 AM,11/06/2017 07:40:00 PM,64,Male,Black,false,ACCIDENT,PROBABLE HEROIN AND COCAINE TOXICITY,NaN,NaN,NaN,False,true,546 GREGORY,CHICAGO HEIGHTS,-87.6641661,41.5094386,57421,"(41.5094386, -87.6641661)"
22388,ME2017-05398,11/16/2017 10:25:00 PM,11/16/2017 10:42:00 PM,46,Male,Black,false,ACCIDENT,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,False,true,6 N. HAMLIN AVE.,CHICAGO,-87.7208386,41.8809507,69761,"(41.8809507, -87.7208386)"
22391,ME2017-05481,11/23/2017 02:50:00 AM,11/23/2017 02:57:00 AM,51,Male,Black,false,ACCIDENT,"COMBINED DRUG (HEROIN, FENTANYL, ACETYL FENTAN...",NaN,NaN,NaN,False,true,5035 S KING #353,CHICAGO,NaN,NaN,66610,NaN
22394,ME2017-05553,11/26/2017 09:20:00 PM,11/26/2017 09:35:00 PM,54,Male,Black,false,ACCIDENT,"COMBINED DRUG TOXICITY (ACRYL FENTANYL, DESPRO...",NaN,NaN,NaN,False,true,2710 S STATE ST #203,CHICAGO,-87.6270059,41.844142,67389,"(41.844142, -87.6270059)"
22395,ME2017-05579,11/29/2017 10:30:00 AM,11/29/2017 10:54:00 AM,55,Male,White,false,ACCIDENT,PROBABLE HEROIN TOXICITY,NaN,NaN,NaN,False,true,"3216 N. Cicero Avenue, Eleanor Hotel Room 414S",CHICAGO,-87.7472492,41.9394196,74075,"(41.9394196, -87.7472492)"
22409,ME2017-05858,12/15/2017 06:25:00 PM,12/15/2017 06:41:00 PM,23,Male,White,false,ACCIDENT,"COMBINED DRUG TOXICITY (HEROIN, METHOXYACETYL ...",NaN,NaN,NaN,False,true,3056 N GRESHAM AVE #2,CHICAGO,-87.7135002,41.9372643,75348,"(41.9372643, -87.7135002)"
22410,ME2017-05881,12/16/2017 11:00:00 PM,12/16/2017 11:32:00 PM,62,Female,Black,false,ACCIDENT,"COMBINED DRUG TOXICITY (HEROIN, FENTANYL)",NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,true,5432 W. HARRISON,CHICAGO,-87.7607525,41.8731088,78774,"(41.8731088, -87.7607525)"
22414,ME2017-05979,12/23/2017 09:00:00 AM,12/23/2017 10:00:00 AM,56,Male,Black,false,ACCIDENT,COMBINED DRUG (FENTANYL AND PROBABLE HEROIN) T...,NaN,NaN,NaN,False,true,"3530 S. Lake Park, Apt. 301",CHICAGO,-87.6084855,41.830097,76605,"(41.830097, -87.6084855)"
22418,ME2017-06091,12/29/2017 10:50:00 AM,12/29/2017 11:05:00 AM,46,Male,Black,false,ACCIDENT,"HEROIN, FENTANYL, AND ACETYL FENTANYL TOXICITY",NaN,NaN,NaN,False,true,8948 S THROOP,CHICAGO,-87.6559258,41.7308491,68667,"(41.7308491, -87.6559258)"
22438,ME2018-00365,01/18/2018 05:30:00 PM,01/18/2018 05:58:00 PM,39,Female,Black,false,ACCIDENT,"COMBINED QUETIAPINE, HYDROXYZINE, CITALOPRAM, ...",NaN,NaN,NaN,False,False,646 E 73RD ST #1,CHICAGO,-87.6084686,41.7623551,71295,"(41.7623551, -87.6084686)"
22445,ME2018-00483,01/24/2018 08:40:00 AM,01/24/2018 08:51:00 AM,56,Male,White,true,ACCIDENT,"TRAZODONE, DIAZEPAM, AND TEMAZEPAM TOXICITY",NaN,NaN,NaN,False,False,3921 W. 60TH Street,CHICAGO,-87.721399,41.783948,72381,"(41.783948, -87.721399)"
22446,ME2018-00495,01/24/2018 04:00:00 PM,01/24/2018 04:14:00 PM,54,Male,Black,false,ACCIDENT,COMBINED DRUG (HEROIN AND CYCLOPROPYL FENTANYL...,NaN,NaN,NaN,False,true,2830 Burlington Street,CHICAGO,NaN,NaN,67387,NaN
22452,ME2018-00563,01/29/2018 09:26:00 AM,01/29/2018 09:38:00 AM,57,Male,White,false,SUICIDE,POBABLE INSULIN TOXICITY,NaN,NaN,NaN,False,False,10827 Mississippi Court,ORLAND PARK,-87.8817391,41.5658323,64252,"(41.5658323, -87.8817391)"
22460,ME2018-00720,02/08/2018 10:30:00 AM,02/08/2018 10:48:00 AM,48,Male,Black,false,ACCIDENT,COMBINED CYCLOPROPYL FENTANYL AND ETHANOL TOXI...,NaN,NaN,NaN,False,true,1534 N. CENTRAL Avenue,CHICAGO,-87.7662074,41.9086402,78043,"(41.9086402, -87.7662074)"
22461,ME2018-00758,02/10/2018 07:55:00 PM,02/10/2018 08:20:00 PM,58,Male,Black,false,ACCIDENT,FENTANYL TOXICITY,NaN,NaN,NaN,False,true,4151 SOUTH BURKLEY APT 1S,CHICAGO,NaN,NaN,78607,NaN
22473,ME2018-00968,02/21/2018 11:12:00 PM,02/21/2018 11:20:00 PM,35,Female,White,true,ACCIDENT,"COMBINED DRUG (1,1-DIFLUOROETHANE, HYDROCODONE...",NaN,NaN,NaN,False,true,5648 W. 63RD PLACE APT 2R,CHICAGO,-87.763618,41.7773644,72997,"(41.7773644, -87.763618)"
22483,ME2017-04147,09/05/2017 02:00:00 AM,09/05/2017 02:19:00 AM,55,Male,Black,false,ACCIDENT,COMBINED DRUG (HEROIN AND FENTANYL) TOXICITY,NaN,NaN,NaN,False,true,6364 Martin Luther King Drive,CHICAGO,NaN,NaN,69080,NaN
22484,ME2017-04211,09/08/2017 03:48:00 PM,09/08/2017 04:03:00 PM,50,Male,Black,false,ACCIDENT,COMBINED DRUG (FENTANYL AND ACETYL FENTANYL) T...,NaN,NaN,NaN,False,true,8539 S BENNETT AVE #2,CHICAGO,-87.5781311,41.7399518,67868,"(41.7399518, -87.5781311)"
22488,ME2017-04339,09/14/2017 07:37:00 PM,09/14/2017 06:52:00 PM,47,Male,Black,false,ACCIDENT,FENTANYL TOXICITY,NaN,NaN,NaN,False,true,4938 Werst Ferdinand,CHICAGO,NaN,NaN,75435,NaN
22495,ME2018-01119,02/24/2018 11:23:00 PM,03/02/2018 02:03:00 PM,34,Male,White,false,ACCIDENT,COMPLICATIONS OF OPIOIDS AND AMPHETAMINES TOXI...,NaN,NaN,NaN,False,true,1920 NERGE RD,ELK GROVE VILLAGE,-88.0570944,41.9998221,59706,"(41.9998221, -88.0570944)"
22503,ME2018-01555,03/29/2018 12:15:00 PM,03/29/2018 12:35:00 PM,61,Female,Black,false,ACCIDENT,"COCAINE, METHADONE, HEROIN, FENTANYL AND ACETY...",NaN,NaN,NaN,False,true,"7318 S. Emerald, 1st Floor",CHICAGO,-87.6433821,41.7609956,69247,"(41.7609956, -87.6433821)"
22541,ME2018-02008,04/08/2018 06:20:00 AM,04/27/2018 12:10:00 AM,63,Male,White,true,ACCIDENT,COMPLICATIONS OF INHALATIONAL INJURY AND CARBO...,NaN,NaN,NaN,False,False,2454 S Spaulding,CHICAGO,-87.7078396,41.8464952,70539,"(41.8464952, -87.7078396)"
22550,ME2018-01990,04/26/2018 04:17:00 AM,04/26/2018 04:29:00 AM,34,Male,White,true,ACCIDENT,"COMBINED DRUG (FENTANYL, CYCLOPROPYLFENTANYL, ...",NaN,NaN,NaN,False,true,4204 W Potomac,CHICAGO,-87.7315699,41.904603,78368,"(41.904603, -87.7315699)"
22573,ME2018-02061,03/31/2018 12:00:00 PM,04/05/2018 05:30:00 PM,64,Male,White,false,ACCIDENT,"COMPLICATIONS OF COMBINED DRUG (ETHANOL, BENZO...",NaN,NaN,NaN,False,true,2919 N. Kilpatrick,CHICAGO,-87.7439579,41.9340212,72802,"(41.9340212, -87.7439579)"

### Okay, toxicity deaths (overdoses) are mostly accidents. Let's look at the first 30 accidental deaths involving toxicity.

- *Tip: Remember your parentheses!*

In [53]:
df[df["Primary_Cause"].str.contains("TOXICITY").fillna(False)].head(30)

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
16,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,False,true,6547 W. 111TH APT W-27,WORTH,-87.7817317,41.6896403,63784,"(41.6896403, -87.7817317)"
46,ME2018-00910,02/19/2018 08:00:00 PM,02/19/2018 08:22:00 PM,56,Male,Black,false,ACCIDENT,COMBINED DRUG (COCAINE AND HEROIN) TOXICITY,NaN,NaN,NaN,False,true,7724 SOUTH LOOMIS BLVD #1,CHICAGO,-87.6589318,41.7532818,69589,"(41.7532818, -87.6589318)"
52,ME2018-00400,01/20/2018 11:15:00 AM,01/20/2018 11:57:00 AM,19,Male,White,false,ACCIDENT,HEROIN TOXICITY,NaN,NaN,NaN,False,true,"5719 S. Kimbark, Apt. 3",CHICAGO,-87.5941419,41.7907435,77880,"(41.7907435, -87.5941419)"
54,ME2018-00643,02/03/2018 10:45:00 AM,02/03/2018 11:11:00 AM,35,Male,White,false,ACCIDENT,"ETHANOL AND COMBINED DRUG (PROBABLE HEROIN, CY...",NaN,NaN,NaN,False,true,"2540 N. Manheim Road, Rm#215",FRANKLIN PARK,NaN,NaN,77879,NaN
55,ME2018-00671,02/05/2018 12:00:00 AM,02/05/2018 12:10:00 AM,27,Male,White,false,ACCIDENT,COMBINED FENTANYL AND PROBABLE HEROIN TOXICITY,NaN,NaN,OBESITY,False,true,3435 W. VAN BUREN,CHICAGO,-87.7119935,41.8753913,77910,"(41.8753913, -87.7119935)"
66,ME2018-01129,03/03/2018 03:45:00 AM,03/03/2018 04:31:00 AM,34,Male,Black,false,ACCIDENT,ACUTE ETHANOL TOXICITY,NaN,NaN,NaN,False,False,7899 SOUTH SHORE,CHICAGO,-87.5481134,41.7520559,68080,"(41.7520559, -87.5481134)"
70,ME2018-01356,03/15/2018 01:31:00 PM,03/15/2018 01:44:00 PM,26,Male,White,false,ACCIDENT,"FENTANYL, HEROIN, AND ALPRAZOLAM TOXICITY",NaN,NaN,NaN,False,true,710 N. 4TH AVENUE,MAYWOOD,-87.8385636,41.8939818,77870,"(41.8939818, -87.8385636)"
91,ME2017-05713,12/07/2017 09:00:00 AM,12/07/2017 09:33:00 AM,43,Male,White,false,SUICIDE,"COMBINED ALPRAZOLAM, HYDROCODONE, ACETAMINOPHE...",NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,true,"920 Ridge Square, Unit 209",ELK GROVE VILLAGE,-87.9895624,42.0033733,59870,"(42.0033733, -87.9895624)"
94,ME2018-01560,03/29/2018 06:50:00 PM,03/29/2018 07:12:00 PM,38,Male,Asian,false,ACCIDENT,COCAINE AND FENTANYL TOXICITY,NaN,NaN,NaN,False,true,535 N MICHIGAN AVE #2705,CHICAGO,-87.6235405,41.8919752,66297,"(41.8919752, -87.6235405)"
100,ME2018-01570,03/30/2018 03:33:00 PM,03/30/2018 04:20:00 PM,50,Male,White,false,ACCIDENT,"COCAINE, FENTANYL AND ACETYL FENTANYL TOXICITY",NaN,NaN,NaN,False,true,1042 N. KNOLLWOOD DR. UNIT A,SCHAUMBURG,-88.1382195,42.0445787,62417,"(42.0445787, -88.1382195)"
103,ME2018-01574,03/30/2018 10:43:00 PM,03/30/2018 11:03:00 PM,40,Female,White,false,ACCIDENT,"COMBINED DRUG (FENTANYL, METHADONE, AND ALPRAZ...",NaN,NaN,NaN,False,true,4345 AUTHUR AVE.,BROOKFIELD,NaN,NaN,63618,NaN
107,ME2018-01103,03/01/2018 02:02:00 PM,03/01/2018 02:45:00 PM,68,Male,Black,false,ACCIDENT,COMBINED DRUG (FENTANYL AND METHADONE) TOXICITY,NaN,NaN,NaN,False,true,1541 SOUTH HAMLIN,CHICAGO,-87.7198186,41.8595195,78255,"(41.8595195, -87.7198186)"
108,ME2018-02197,05/07/2018 09:27:00 AM,05/08/2018 05:23:00 AM,38,Female,White,false,ACCIDENT,FENTANYL AND COCAINE TOXICITY,NaN,NaN,NaN,False,true,15611 DIXIE HWY (APT 2),HARVEY,-87.6693327,41.6057103,78760,"(41.6057103, -87.6693327)"
109,ME2017-05182,11/04/2017 08:45:00 PM,11/04/2017 09:03:00 PM,50,Male,Black,false,ACCIDENT,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,False,true,5319 S. WALCOTT,CHICAGO,-87.6717184,41.7970338,77967,"(41.7970338, -87.6717184)"
110,ME2017-05643,12/02/2017 02:50:00 PM,12/02/2017 02:44:00 PM,45,Male,White,false,ACCIDENT,"COMBINED DRUG (HEROIN, FENTANYL, AND ACETYL FE...",NaN,NaN,NaN,False,true,4023 West Congress Parkway,CHICAGO,-87.7263732,41.8742991,77943,"(41.8742991, -87.7263732)"
129,ME2018-02201,04/10/2018 01:14:00 AM,04/14/2018 09:20:00 PM,57,Female,White,false,ACCIDENT,COMBINED DRUG (BENZODIAZEPINE AND PROBABLE HER...,NaN,NaN,NaN,False,true,411 FOREST PRESERVE DRIVE.,WOOD DALE,NaN,NaN,78485,NaN
162,ME2018-02220,05/02/2018 12:00:00 PM,05/05/2018 03:17:00 PM,35,Female,White,false,ACCIDENT,COMPLICATIONS OF METHADONE TOXICITY,NaN,NaN,NaN,False,true,15715 INDEPENDENCE CT,OAK FOREST,-87.7574509,41.6059968,78072,"(41.6059968, -87.7574509)"
176,ME2018-00926,02/20/2018 12:00:00 PM,02/20/2018 12:36:00 PM,39,Male,White,true,ACCIDENT,COMBINED HEROIN AND FENTANYL TOXICITY,NaN,NaN,NaN,False,true,4345 SOUTH PACKERS,NaN,-87.6576873,41.8147004,78047,"(41.8147004, -87.6576873)"
194,ME2017-04357,09/16/2017 03:46:00 AM,09/16/2017 04:01:00 AM,66,Male,White,false,ACCIDENT,FENTANYL AND ACETYL FENTANYL TOXICITY,NaN,NaN,NaN,False,true,7835 WEST CRESSETT,ELMWOOD PARK,-87.8224024,41.9301994,78115,"(41.9301994, -87.8224024)"
229,ME2016-03209,06/30/2016 09:45:00 AM,06/30/2016 10:02:00 AM,57,Male,White,false,ACCIDENT,ACUTE OXYCODONE AND OXYMORPHONE TOXICITY,NaN,NaN,NaN,False,true,7101 Emerson Street,MORTON GROVE,-87.8036954,42.0517323,60635,"(42.0517323, -87.8036954)"
233,ME2018-01362,03/16/2018 01:53:00 AM,03/16/2018 02:06:00 AM,49,Male,White,false,ACCIDENT,"COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TO...",NaN,NaN,NaN,False,true,945 W. BELMONT AVE.,CHICAGO,-87.6532951,41.9398725,78209,"(41.9398725, -87.6532951)"
234,ME2018-01822,04/15/2018 09:00:00 AM,04/15/2018 09:21:00 AM,57,Male,White,false,ACCIDENT,"ALCOHOL, TEMAZEPAM AND ALPRAZOLAM TOXICITY",NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,252 W. JENNIFER LANE #1,PALATINE,-88.0498716,42.1246964,78220,"(42.1246964, -88.0498716)"
244,ME2018-02302,05/10/2018 05:00:00 PM,05/14/2018 02:50:00 PM,61,Female,White,false,ACCIDENT,COMPLICATIONS OF OPIATE AND BENZODIAZEPINE TOX...,NaN,NaN,"DIABETES MELLITUS, HYPERTENSIVE CARDIOVASCULAR...",False,true,3036 W. BELMONT,CHICAGO,-87.7042375,41.9395819,78349,"(41.9395819, -87.7042375)"
253,ME2017-00383,01/22/2017 09:30:00 AM,01/22/2017 10:00:00 AM,53,Female,White,false,ACCIDENT,"ETHANOL AND COMBINED DRUG (HYDROCODONE, LEVETI...",NaN,NaN,NaN,False,true,2519 NORTH ROCKWELL STREET,CHICAGO,-87.6923633,41.9272948,74629,"(41.9272948, -87.6923633)"
256,ME2017-06107,12/27/2017 06:18:00 AM,12/30/2017 07:28:00 AM,27,Male,White,false,ACCIDENT,"FENTANYL, DIAZEPAM, LORAZEPAM, AND SERTRALINE ...",NaN,NaN,HYPOTHERMIA DUE TO COLD EXPOSURE,False,true,135 E OAK ST,CHICAGO,-87.6246305,41.9007545,78228,"(41.9007545, -87.6246305)"
354,ME2018-02380,05/20/2018 09:25:00 AM,05/20/2018 10:03:00 AM,40,Male,Black,false,ACCIDENT,ETHANOL TOXICITY,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC E...",False,False,6803 S. Clyde,CHICAGO,-87.5739333,41.7715777,78574,"(41.7715777, -87.5739333)"
357,ME2018-00475,01/23/2018 09:42:00 PM,01/23/2018 09:59:00 PM,53,Female,Black,false,ACCIDENT,COCAINE TOXICITY,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,14134 PAGE ST.,DIXMOOR,-87.6598032,41.6322383,58259,"(41.6322383, -87.6598032)"
389,ME2018-01138,03/03/2018 09:30:00 AM,03/03/2018 10:13:00 AM,27,Male,Black,false,ACCIDENT,FENTANYL AND ALPRAZOLAM TOXICITY,NaN,NaN,NaN,False,true,7829 S. PEORIA 2ND FLOOR APT,CHICAGO,-87.6462021,41.7515321,68896,"(41.7515321, -87.6462021)"
397,ME2018-01232,03/08/2018 02:10:00 PM,03/08/2018 02:42:00 PM,36,Male,White,true,ACCIDENT,"COMBINED DRUG (CARFENTANIL, FURANYL FENTANYL, ...",NaN,NaN,NaN,False,true,1600 N. WESTERN AND NORTH AVE.,CHICAGO,-87.6873004,41.9103425,69942,"(41.9103425, -87.6873004)"
399,ME2018-01248,03/09/2018 12:00:00 AM,03/09/2018 11:41:00 AM,45,Female,Black,false,ACCIDENT,COCAINE TOXICITY,NaN,NaN,NaN,False,False,3554 W Ohio,CHICAGO,-87.7156869,41.8918636,69058,"(41.8918636, -87.7156869)"

## Wow, that's a lot of drug overdoses. What's more popular for overdosing: heroin, fentanyl, cocaine, or ethanol?

You can count something like "COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TOXICITY" under both ethanol and fentanyl.

- *Tip: Search for them individually*

In [54]:
df[df["Primary_Cause"].str.contains("HEROIN").fillna(False)]["Primary_Cause"].count()

2022

In [55]:
df[df["Primary_Cause"].str.contains("FENTANYL").fillna(False)]["Primary_Cause"].count()

1493

In [56]:
df[df["Primary_Cause"].str.contains("COCAINE").fillna(False)]["Primary_Cause"].count()

1064

In [57]:
df[df["Primary_Cause"].str.contains("ETHANOL").fillna(False)]["Primary_Cause"].count()

1327

# Cleaning up Primary Cause

Let's stop investigating for a second and maybe clean up this "Primary Cause" column.

## What are the most common Primary Cause of death? Include `NaN` values

- *Tip: There is an option that keeps `NaN` values when counting things in a column.*

In [58]:
df.Primary_Cause.value_counts()

ORGANIC CARDIOVASCULAR DISEASE                                                                                        1983
MULTIPLE GUNSHOT WOUNDS                                                                                               1377
HYPERTENSIVE CARDIOVASCULAR DISEASE                                                                                   1177
ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                                                974
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                                   960
MULTIPLE INJURIES                                                                                                      941
HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                               460
PENDING                                                                                                                452
GUNSHOT WOUND OF HEAD                                                                                                  440
HANGING                                                                                                                323
MULTIPLE BLUNT FORCE INJURIES                                                                                          299
HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                                                                298
HEROIN TOXICITY                                                                                                        286
ASPHYXIA                                                                                                               255
UNDETERMINED                                                                                                           242
CLOSED HEAD INJURIES                                                                                                   217
CHRONIC ETHANOLISM                                                                                                     205
CORONARY ATHEROSCLEROSIS                                                                                               203
DROWNING                                                                                                               185
COMPLICATIONS OF FALL                                                                                                  181
COMPLICATIONS OF CHRONIC ETHANOLISM                                                                                    177
COMPLICATIONS OF MULTIPLE INJURIES                                                                                     160
ASPHYXIATION                                                                                                           151
ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                                                                                 140
GUNSHOT WOUND OF THE HEAD                                                                                              132
PULMONARY THROMBOEMBOLISM                                                                                              122
GUNSHOT WOUND OF CHEST                                                                                                 120
DIABETIC KETOACIDOSIS                                                                                                  107
FENTANYL TOXICITY                                                                                                      103
COCAINE TOXICITY                                                                                                        95
                                                                                                                      ...
COMBINED DRUG (DIPHENHYDRAMINE, CITALOPRAM/ESCITALOPRAM, NORDIAZEPAM, AND 7-AMINO CLONAZEPAM) AND ETHANOL TOXICITY       1
COMBINED DRUG TOXICITY (INCLUDING METHADONE, SERTRALINE, TEMAZEPAM, AND ALPRAZOLAM)                                      1
PROBABLE STROKE CAUSING FALL                                                                                             1
ETHANOL, METHADONE, AND BENZODIAZEPINE INTOXICATION                                                                      1
COMBINED COCAINE, COCAETHYLENE, ETHANOL, HEROIN, ALPRAZOLAM AND DEXTRO/LEVO METHORPHAN TOXICITY                          1
AQUIRED IMMUNE DEFICIENCY SYNDROME                                                                                       1
BUTALBITAL AND CLONAZEPAM TOXICITY                                                                                       1
ACUTE MULTI-DRUG (DIAZEPAM, ZOLPIDEM, FENTANYL) AND ETHANOL TOXICITY                                                     1
PROBABLE ANGIOEDEMA OF UNKNOWN ETIOLOGY                                                                                  1
COMBINED DRUG (CODEINE, MORPHINE AND ETHANOL) TOXICITY                                                                   1
COMBINED DRUG (COCAINE, METHAMPHETAMINE, HEROIN, ALPRAZOLAM, N-ETHYL PENTYLONE) TOXICITY                                 1
COMBINED DRUG (FENTANYL, DIAZEPAM, NORDIAZEPAM, LORAZEPAM) TOXICITY                                                      1
HEMORRHAGIC STROKE                                                                                                       1
GUNSHOT WOUND OF THE NECK INTO CHEST AND BACK                                                                            1
COMPLICATIONS FOLLOWING BLUNT FORCE INJURIES TO LEFT HIP                                                                 1
HYPERTENSIVE CARDOIOVASCULAR DISEASE                                                                                     1
COMPLICATIONS OF COMBINED DRUG (FENTANYL, HEROIN, AND HYDROCODONE) INTOXICATION                                          1
MASSIVE INTERNAL BLEEDING                                                                                                1
COMBINED CYCLOPROPYL FENTANYL AND DIAZEPAM TOXICITY                                                                      1
MULTIPLE DRUG TOXICITY (HEROIN, ETHANOL, ALPRAZOLAM)                                                                     1
COMBINED DRUG (ETHANOL, ALPRAZOLAM, AND HEROIN) TOXICITY                                                                 1
GUNSHOT WOUND OF RIGHT ARM, INTO TORSO                                                                                   1
COMBINED FENTANYL AND DESPROPIONYL FENTANYL TOXICITY                                                                     1
COMBINED DRUG (COCAINE, HEROIN AND ALCOHOL) TOXICITY                                                                     1
COMBINED DRUG TOXICITY (FENTANYL, PROBABLE HEROIN, CLONAZEPAM)                                                           1
HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASULAR DISEASE                                                                      1
GUNSHOT WOUND OF CHIN                                                                                                    1
HEMORRHAGE DUE TO SHARP FORCE INJURIES OF THE RIGHT FOREARM                                                              1
CONGENITAL ANOMALY OF LEFT CORONARY OSTIUM                                                                               1
COCAINE AND ALPRAZOLAM TOXICITY                                                                                          1
Name: Primary_Cause, Length: 3994, dtype: int64

## That was horrible looking. I don't want to read through that - how many `NaN` causes of death are there?

- *Tip: You can use `isnull()` to see if it's missing data, but how do you count the results?*

In [59]:
df.Primary_Cause.isnull().value_counts()

False    22511
True       124
Name: Primary_Cause, dtype: int64

## Remove all rows where the primary cause of death has not been filled out.

- *Tip: confirm that you have 22510 rows when you're done*

In [60]:
df.Primary_Cause.dropna()

0                                            Primary Cause
6                                        MULTIPLE INJURIES
7                                    GUNSHOT WOUND TO HEAD
8                                                  PENDING
9                                                  PENDING
10                                                 PENDING
11                                   GUNSHOT WOUND OF HEAD
12                                       MULTIPLE INJURIES
13                                       MULTIPLE INJURIES
14                         COMPLICATIONS OF MORBID OBESITY
15                                 MULTIPLE GUNSHOT WOUNDS
16       COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...
17                           MULTIPLE SHARP FORCE INJURIES
18                                    CLOSED HEAD INJURIES
19                          ORGANIC CARDIOVASCULAR DISEASE
20                                 MULTIPLE GUNSHOT WOUNDS
21                        MULTIPLE STAB AND INCISED WOUNDS
22                                                 PENDING
23                                     STAB WOUND OF CHEST
24                                       MULTIPLE INJURIES
25                                       CEREBRAL INJURIES
26                                                 PENDING
28       ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...
29       HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...
33                                                 PENDING
34                                                 PENDING
35                          ORGANIC CARDIOVASCULAR DISEASE
36                                 MULTIPLE GUNSHOT WOUNDS
37                               GUNSHOT WOUND OF THE HEAD
38                                 MULTIPLE GUNSHOT WOUNDS
                               ...
22603                                              PENDING
22604                                COMPLICATIONS OF FALL
22605    HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...
22606                                    NON-HUMAN REMAINS
22607    HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...
22608                                              PENDING
22609                       ORGANIC CARDIOVASCULAR DISEASE
22610                                              PENDING
22611                        MULTIPLE BLUNT FORCE INJURIES
22612                       ORGANIC CARDIOVASCULAR DISEASE
22613                       ORGANIC CARDIOVASCULAR DISEASE
22614                                              PENDING
22615                                              PENDING
22616                                              PENDING
22617                                              PENDING
22618                                              PENDING
22619                       ORGANIC CARDIOVASCULAR DISEASE
22620                       ORGANIC CARDIOVASCULAR DISEASE
22622                                              PENDING
22624                                              PENDING
22625                       ORGANIC CARDIOVASCULAR DISEASE
22626                       ORGANIC CARDIOVASCULAR DISEASE
22627                                              PENDING
22628                                              PENDING
22629                       GUNSHOT WOUND OF RIGHT BUTTOCK
22630                                              PENDING
22631                       ORGANIC CARDIOVASCULAR DISEASE
22632                                              PENDING
22633                                GUNSHOT WOUND OF HEAD
22634                       ORGANIC CARDIOVASCULAR DISEASE
Name: Primary_Cause, Length: 22511, dtype: object

# Cardiovascular disease

Cardiovascular disease (heart disease) is the number one or number two killer in America.

### Filter for only rows where cardiovascular disease was a primary cause

- *Tip: I hope you know how to deal with the `NaN` error message by now!*

In [61]:
df[df["Primary_Cause"].str.contains("CARDIOVASCULAR").fillna(False)]

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
19,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
28,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48,Male,White,false,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,False,False,2631 West Rascher Avenue,CHICAGO,-87.6954789,41.9802154,77843,"(41.9802154, -87.6954789)"
29,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76,Male,White,false,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,False,False,8108 ODELL AVENUE,BRIDGEVIEW,-87.8036075,41.7440145,77849,"(41.7440145, -87.8036075)"
35,ME2018-02170,05/06/2018 02:05:00 PM,05/06/2018 02:46:00 PM,64,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,4250 S. PRINCETON APT 412,CHICAGO,-87.6347043,41.8167422,78016,"(41.8167422, -87.6347043)"
44,ME2014-01078,10/18/2014 02:30:00 PM,10/18/2014 03:55:00 PM,67,Male,White,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,610 SOUTH MAWATA,MOUNT PROSPECT,NaN,NaN,61280,NaN
58,ME2018-02186,05/07/2018 12:26:00 PM,05/07/2018 12:53:00 PM,66,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,146 N. CENTRAL #1D,CHICAGO,-87.7654736,41.8836343,78010,"(41.8836343, -87.7654736)"
65,ME2018-00995,02/23/2018 09:35:00 AM,02/23/2018 09:50:00 AM,70,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,5700 NORTH SHERIDAN APT 1003,NaN,-87.6557545,41.9858569,55722,"(41.9858569, -87.6557545)"
67,ME2018-01148,03/03/2018 04:30:00 PM,03/03/2018 05:09:00 PM,58,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,OBESITY,False,False,11011 JORDAN DRIVE,OAK LAWN,NaN,NaN,59051,NaN
72,ME2018-01411,03/19/2018 12:00:00 AM,03/19/2018 11:04:00 AM,59,Female,Black,false,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,"CHRONIC OBSTRUCTIVE PULMONARY DISEASE, DIABETE...",False,False,7804 South Maryland 1st floor,CHICAGO,-87.6040862,41.7530066,77882,"(41.7530066, -87.6040862)"
73,ME2018-01910,05/01/2018 10:50:00 AM,05/01/2018 10:59:00 AM,65,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NON-TRAUMATIC SEIZURE DISORDER,False,False,841 Williams Street #1D,CALUMET CITY,-87.5456329,41.599656,77889,"(41.599656, -87.5456329)"
78,ME2018-02047,05/04/2018 01:03:00 PM,05/04/2018 01:13:00 PM,77,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1127 DARTMOUTH RD,FLOSSMOOR,-87.6659691,41.5417673,78304,"(41.5417673, -87.6659691)"
81,ME2014-00002,08/11/2014 09:35:00 AM,08/11/2014 01:00:00 PM,57,Male,White,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,345 W. Fullerton Pkwy #503,CHICAGO,-87.6382754,41.9252778,67261,"(41.9252778, -87.6382754)"
82,ME2014-00003,08/11/2014 09:05:00 AM,08/11/2014 09:40:00 AM,74,Male,Black,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,520 E. 47th Street Room 325,CHICAGO,-87.613031,41.8094993,76196,"(41.8094993, -87.613031)"
85,ME2014-00006,08/10/2014 07:15:00 AM,08/10/2014 08:00:00 AM,82,Female,White,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,4037 North Major,CHICAGO,-87.769174,41.9543011,73326,"(41.9543011, -87.769174)"
98,ME2018-01567,03/30/2018 10:49:00 AM,03/30/2018 10:54:00 AM,73,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"3532 WENONAH AVENUE, BASEMENT",BERWYN,-87.7990951,41.8274439,57283,"(41.8274439, -87.7990951)"
106,ME2018-02195,05/07/2018 11:30:00 PM,05/08/2018 11:57:00 PM,44,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,222 S. HAMLIN (2ND FLOOR APT B18 ),CHICAGO,-87.7212533,41.8773392,78100,"(41.8773392, -87.7212533)"
123,ME2018-02117,05/03/2018 09:00:00 AM,05/03/2018 09:15:00 AM,78,Female,Black,false,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,408 S Scovel; unit 1N,OAK PARK,-87.7851498,41.8870064,78104,"(41.8870064, -87.7851498)"
124,ME2018-02202,05/08/2018 01:26:00 PM,05/08/2018 03:00:00 PM,47,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS,False,False,21329 Illinois Street,MATTESON,-87.7011843,41.501797,78143,"(41.501797, -87.7011843)"
125,ME2018-02207,05/08/2018 01:31:00 PM,05/08/2018 01:49:00 PM,71,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,212 SOUTH OAK PARK AVENUE APT #201,OAK PARK,-87.7938998,41.8844746,78276,"(41.8844746, -87.7938998)"
136,ME2018-02215,05/08/2018 08:28:00 PM,05/08/2018 09:20:00 PM,47,Male,White,true,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS; MORBID OBESITY,False,False,4551 West Altgeld Street,CHICAGO,-87.7411047,41.9260404,78116,"(41.9260404, -87.7411047)"
140,ME2018-02252,05/11/2018 10:55:00 AM,05/11/2018 11:05:00 AM,61,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1856 W CERMAK RD,CHICAGO,-87.6731375,41.8524131,78107,"(41.8524131, -87.6731375)"
152,ME2018-02159,05/05/2018 07:45:00 PM,05/05/2018 08:10:00 PM,77,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,3409 S. 55TH AVENUE,CICERO,-87.7608196,41.8305508,77990,"(41.8305508, -87.7608196)"
171,ME2018-02225,05/09/2018 01:30:00 PM,05/09/2018 01:44:00 PM,70,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"3656 W. HURON STREET, UNIT #507",CHICAGO,-87.7182497,41.8938088,78905,"(41.8938088, -87.7182497)"
172,ME2018-02210,05/08/2018 12:00:00 PM,05/08/2018 12:36:00 PM,73,Female,Black,false,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,"OBESITY, DIABETES MELIITUS, CHRONIC OBSTRUCTIV...",False,False,"4930 S. LANGLEY AVENUE, UNIT #1011",CHICAGO,-87.6092179,41.8050321,78090,"(41.8050321, -87.6092179)"
179,ME2018-02230,05/09/2018 03:43:00 PM,05/09/2018 04:35:00 PM,60,Female,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,24 158TH BUILDING 11 APT 4E,CALUMET CITY,-87.5708611,41.6049219,78040,"(41.6049219, -87.5708611)"
192,ME2018-02234,05/09/2018 08:42:00 PM,05/09/2018 10:34:00 PM,58,Female,White,true,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,DIABETES MELLITUS; METASTATIC BREAST CANCER,False,False,6035 W. FULLERTON AVE,CHICAGO,-87.7771075,41.9235787,78329,"(41.9235787, -87.7771075)"
198,ME2018-02263,05/01/2018 10:00:00 AM,05/01/2018 10:13:00 AM,95,Female,White,false,NaN,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"5219 N. POTAWATOMIE, UNIT 101",CHICAGO,-87.8423531,41.9743293,78171,"(41.9743293, -87.8423531)"
202,ME2018-02213,05/08/2018 09:15:00 PM,05/08/2018 09:35:00 PM,63,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,8528 SOUTH 83RD AVENUE,HICKORY HILLS,-87.8262807,41.7360172,78140,"(41.7360172, -87.8262807)"
210,ME2018-02286,05/13/2018 11:00:00 AM,05/13/2018 11:38:00 AM,81,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,7821 W. 89TH STR. #1W,HICKORY HILLS,-87.8142692,41.7294997,78227,"(41.7294997, -87.8142692)"
214,ME2018-02285,05/13/2018 11:30:00 AM,05/13/2018 12:22:00 PM,48,Male,White,false,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,OBESITY,False,False,17037 GRISSOM DRIVE #2N,TINLEY PARK,-87.8153083,41.5811079,78312,"(41.5811079, -87.8153083)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22544,ME2018-02011,04/16/2018 12:00:00 AM,04/16/2018 03:37:00 PM,55,Male,Black,false,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS,False,False,"7907 S, Eberhart",CHICAGO,-87.6122906,41.7509154,74948,"(41.7509154, -87.6122906)"
22547,ME2018-02014,04/27/2018 03:20:00 PM,04/27/2018 03:42:00 PM,54,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,68 E. WACKER PL,CHICAGO,-87.6253815,41.8870687,63628,"(41.8870687, -87.6253815)"
22553,ME2018-02019,04/27/2018 07:09:00 PM,04/27/2018 07:18:00 PM,69,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,MORBID OBESITY; DIABETES MELLITUS,False,False,449 SANDRA LANE,ELGIN,-88.2557056,42.0280296,60615,"(42.0280296, -88.2557056)"
22556,ME2018-02037,04/27/2018 12:00:00 AM,04/29/2018 12:24:00 PM,94,Male,White,false,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,"END STAGE RENAL DISEASE, CHRONIC OBSTRUCTIVE P...",False,False,2732 N. HAMPDEN,CHICAGO,-87.6424828,41.931412,76983,"(41.931412, -87.6424828)"
22557,ME2018-02038,04/29/2018 12:00:00 PM,04/29/2018 12:23:00 PM,80,Male,Black,false,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,False,False,3333 WEST MAPLE APT 714,CHICAGO,-87.7100524,41.883377,77794,"(41.883377, -87.7100524)"
22559,ME2018-02040,04/29/2018 01:05:00 PM,04/29/2018 01:37:00 PM,72,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,False,1832 187TH STREET,HOMEWOOD,-87.6614767,41.5499918,77782,"(41.5499918, -87.6614767)"
22560,ME2018-02041,04/29/2018 03:00:00 PM,04/29/2018 03:51:00 PM,82,Female,White,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,408 RIDGE CIRCLE,STREAMWOOD,-88.160042,42.0243866,58262,"(42.0243866, -88.160042)"
22565,ME2018-02046,04/29/2018 06:41:00 PM,04/29/2018 06:50:00 PM,80,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,7132 WEST 26TH STREET #02,BERWYN,-87.8024091,41.8428225,57031,"(41.8428225, -87.8024091)"
22569,ME2018-02057,04/29/2018 07:15:00 PM,04/29/2018 07:25:00 PM,62,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,312 N WILLIAM,MOUNT PROSPECT,-87.9288773,42.0731669,60962,"(42.0731669, -87.9288773)"
22570,ME2018-02058,04/22/2018 12:07:00 PM,04/22/2018 12:44:00 PM,65,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1242 LEEWOOD CT,ELGIN,-88.2433353,42.0447586,77642,"(42.0447586, -88.2433353)"
22576,ME2018-02065,04/30/2018 03:45:00 PM,04/30/2018 04:00:00 PM,69,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,END STAGE RENAL DISEASE,False,False,4949 S. COTTAGE GROVE APT 812,CHICAGO,-87.606029,41.8044491,77798,"(41.8044491, -87.606029)"
22577,ME2018-02066,04/30/2018 11:00:00 AM,04/30/2018 11:14:00 AM,75,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,5333 N. SHERIDAN RD. #21B,CHICAGO,-87.6543755,41.9794337,74510,"(41.9794337, -87.6543755)"
22580,ME2018-01213,01/07/2018 07:01:00 PM,01/07/2018 07:41:00 PM,66,Male,Black,false,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES,False,False,6943 SOUTH INDIANA AVENUE,CHICAGO,-87.6198721,41.7679856,72842,"(41.7679856, -87.6198721)"
22589,ME2018-02135,05/03/2018 08:50:00 PM,05/03/2018 09:22:00 PM,64,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,890 OAK WOOD COURT,DES PLAINES,-87.9019049,42.0375718,77892,"(42.0375718, -87.9019049)"
22594,ME2018-02140,05/04/2018 09:50:00 AM,05/04/2018 10:44:00 AM,56,Male,White,true,NATURAL,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,False,False,1301 S 47th Ave,CICERO,-87.7413222,41.8636133,78734,"(41.8636133, -87.7413222)"
22599,ME2018-02082,05/01/2018 10:30:00 AM,05/01/2018 11:15:00 AM,84,Female,Black,false,NaN,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,8906 S. MERRILL,CHICAGO,-87.5722831,41.7331679,68510,"(41.7331679, -87.5722831)"
22600,ME2018-02083,04/04/2018 07:45:00 PM,04/04/2018 08:05:00 PM,63,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,5207 W Fernaird # 3E,CHICAGO,NaN,NaN,75387,NaN
22601,ME2018-02084,05/01/2018 02:06:00 PM,05/01/2018 02:30:00 PM,71,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CHRONIC OBSTRUCTIVE PULMONARY DISEASE, DIABETE...",False,False,5839 S HARLEM AVE #417,CHICAGO,-87.8011736,41.7852787,77786,"(41.7852787, -87.8011736)"
22602,ME2018-02085,05/01/2018 04:06:00 PM,05/01/2018 04:20:00 PM,94,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2470 N. CLARK #508,CHICAGO,-87.6421167,41.9273255,67333,"(41.9273255, -87.6421167)"
22605,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50,Male,White,true,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",False,False,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.6967797,41.8521269,70244,"(41.8521269, -87.6967797)"
22607,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48,Female,Black,false,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,False,False,201 W. 69TH STREET,CHICAGO,-87.6302482,41.768766,72642,"(41.768766, -87.6302482)"
22609,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.6228345,41.8417184,77971,"(41.8417184, -87.6228345)"
22612,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55,Female,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,False,False,1755 HENLEY ST #2N,GLENVIEW,-87.8022124,42.0700695,78280,"(42.0700695, -87.8022124)"
22613,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.8624014,78381,"(41.8624014, -87.640188)"
22619,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.6570785,41.7267165,77789,"(41.7267165, -87.6570785)"
22620,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2058 W. Hutchinson,CHICAGO,-87.6812383,41.9589732,67932,"(41.9589732, -87.6812383)"
22625,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1127 Miller Lane;,BUFFALO GROVE,-87.9784066,42.1347284,77891,"(42.1347284, -87.9784066)"
22626,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.6438762,41.9419529,77939,"(41.9419529, -87.6438762)"
22631,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94,Male,White,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",False,False,16416 EVANS AVENUE,SOUTH HOLLAND,-87.6009945,41.5966344,78272,"(41.5966344, -87.6009945)"
22634,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57,Male,Black,false,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,False,3914 212 PL,MATTESON,-87.7114567,41.5041136,78828,"(41.5041136, -87.7114567)"

### What are the different types?

In [62]:
df[df["Primary_Cause"].str.contains("CARDIOVASCULAR").fillna(False)]["Primary_Cause"].value_counts()

ORGANIC CARDIOVASCULAR DISEASE                                         1983
HYPERTENSIVE CARDIOVASCULAR DISEASE                                    1177
ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                 974
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                    960
HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                460
HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                 298
ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                                  140
HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                     90
ORGANIC  CARDIOVASCULAR DISEASE                                          77
HYPERTENSIVE ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                      38
ORGANIC CARDIOVASCULAR DISEASE.                                          19
ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULAR DISEASE                  16
ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE.                                 15
HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE.                15
ARTERIOSLCEROTIC CARDIOVASCULAR DISEASE                                   9
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DIASEASE                     9
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE.                     7
VALVULAR CARDIOVASCULAR DISEASE                                           4
HYPERTENSIVE CARDIOVASCULAR DISEASE.                                      4
HYPERTENSIVE AND OBESITY-RELATED CARDIOVASCULAR DISEASE                   4
HYPERTENSIVE, ARTERIOSCLEROTIC AND VALVULAR CARDIOVASCULAR DISEASE        3
HYPERTENSIC ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                       3
HYPERTENSIVE, ATHEROSCLEROTIC AND VALVULAR CARDIOVASCULAR DISEASE         3
OBESITY-RELATED CARDIOVASCULAR DISEASE                                    3
HYPERTENSIVE ARTERIOSCLEROSIS CARDIOVASCULAR DISEASE                      3
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISESE                       3
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DIS.                         3
HYPERTENSIVE AND VALVULAR CARDIOVASCULAR DISEASE                          3
ARTERIOSCLEROTIC  CARDIOVASCULAR DISEASE                                  2
HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR                          2
                                                                       ...
PROBABLE ORGANIC CARDIOVASCULAR DISEASE                                   1
PROBABLE DYSRHYTHMOGENIC CARDIOVASCULAR DISEASE                           1
HYPERTENSIVE ARTERIOLSCEROTIC CARDIOVASCULAR DISEASE                      1
ATHEROSCEROTIC CARDIOVASCULAR DISEASE                                     1
HYPEERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                     1
ARTERIOSCLEROTIC CARDIOVASCULAR DISESE                                    1
HYPERTENSIVE ATHEROSCLEROTIC CARDIOVASCULAR DISEASE.                      1
ORGANIC ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                           1
ARTTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                  1
HYPERTENSIVS CARDIOVASCULAR DISEASE                                       1
ARTERIOACLEROTIC CARDIOVASCULAR DISEASE                                   1
HYPERTENSION CARDIOVASCULAR DISEASE                                       1
ATHEROSCLEROTIC AND VALVULAR CARDIOVASCULAR DISEASE                       1
ISCHEMIC CARDIOVASCULAR DISEASE                                           1
ATHEROSCLERTOIC CARDIOVASCULAR DISEASE                                    1
ATHERSCLEROTIC CARDIOVASCULAR DISEASE                                     1
ORGANIC ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                            1
HYPERTENSIVE ARTERIOSCELROTIC CARDIOVASCULAR DIEASE.                      1
HYPERTENSIVE ARTERIOSCLERTIC CARDIOVASCULAR DISEASE                       1
ARTERIOSLEROTIC CARDIOVASCULAR DISEASE                                    1
HYPERTENSIVE ARTERIOSCLERITIC CARDIOVASCULAR DISEASE                      1
CARDIOVASCULAR DISEASE, UNSPECIFIED                                       1
ORGANIC CARDIOVASCULAR  DISEASE                                           1
ATHEROSCELROTIC CARDIOVASCULAR DISEASE.                                   1
HYPERTENSIVE ARTERIOSCLOEROTIC CARDIOVASCULAR DISEASE                     1
ARTERIOSCLEROTIC CARDIOVASCULAR  DISEASE                                  1
HYPERTESIVE CARDIOVASCULAR DISEASE                                        1
ARTERIOSCLEROTIC AND HYPERTENSIVE CARDIOVASCULAR DISEASE                  1
HYPERTENSIVE, VALVULAR, AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE       1
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR                              1
Name: Primary_Cause, Length: 131, dtype: int64

### Replace all of those with a nice simple 'CARDIOVASCULAR DISEASE'

- *Tip: you can use `.replace` or `.str.replace`, but they each involve different things! I suggest `.replace`, it looks a little cleaner in this situation*
- *Tip: for `.replace`, you need to give it more options than usual*
- *Tip: for `.str.replace`, it won't automatically save back into the column, you need to do that yourself*

In [63]:
df['Primary_Cause'] = df.Primary_Cause.str.replace(".*CARDIOVASCULAR.*", "CARDIOVASCULAR DISEASE")
df

,Case_Number,Date_of_Incident,Date of Death,Age,Gender,Race,Latino,Manner_of_Death,Primary_Cause,Primary_Cause_Line_B,Primary_Cause_Line_C,Secondary_Cause,Gun_Related,Opioid_Related,Incident_Address,Incident_City,longitude,latitude,OBJECTID,location
0,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
1,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,20468,NaN
2,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,2110 W. 21ST PL #1,CHICAGO,-87.6788449,41.8532787,77827,"(41.8532787, -87.6788449)"
3,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
4,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64,Female,White,false,NaN,NaN,NaN,NaN,NaN,False,False,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.7281769,41.9574677,77823,"(41.9574677, -87.7281769)"
5,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,3947 W. LEXINGTON STREET,CHICAGO,-87.7247386,41.8714515,77822,"(41.8714515, -87.7247386)"
6,ME2018-02153,03/20/2018 12:00:00 AM,05/05/2018 01:28:00 AM,28,Male,Black,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,77903,NaN
7,ME2017-00971,02/25/2017 07:48:00 AM,02/25/2017 09:20:00 AM,55,Male,White,false,UNDETERMINED,GUNSHOT WOUND TO HEAD,NaN,NaN,NaN,true,False,209 E. LAKE SHORE DRIVE,CHICAGO,-87.6214206,41.900571,77930,"(41.900571, -87.6214206)"
8,ME2018-02147,05/04/2018 10:04:00 PM,05/04/2018 10:25:00 PM,47,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1905 S. SPAULDING #1,CHICAGO,-87.707465,41.855148,78042,"(41.855148, -87.707465)"
9,ME2018-02152,05/05/2018 01:47:00 AM,05/05/2018 02:54:00 AM,3,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,1012 N. AVERS AVENUE APT#2,CHICAGO,NaN,NaN,78299,NaN
10,ME2018-02151,05/05/2018 06:00:00 AM,05/05/2018 06:35:00 AM,62,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,910 W 76TH 3RD FLOOR,CHICAGO,-87.6470422,41.7561236,78337,"(41.7561236, -87.6470422)"
11,ME2018-02148,05/04/2018 11:55:00 PM,05/05/2018 12:16:00 AM,55,Male,Black,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,"300 NORTH STATE, APT 6021",CHICAGO,-87.6290778,41.8879298,78480,"(41.8879298, -87.6290778)"
12,ME2014-00679,09/24/2014 09:06:00 PM,09/25/2014 01:52:00 AM,52,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,724 Railroad Street,JOLIET,NaN,NaN,62692,NaN
13,ME2018-01106,03/01/2018 01:58:00 PM,03/01/2018 05:00:00 PM,37,Male,White,false,ACCIDENT,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,290 EASTBOUND AT MILE MARKER POST 14,BELLWOOD,NaN,NaN,60932,NaN
14,ME2018-01125,03/02/2018 10:45:00 PM,03/02/2018 11:09:00 PM,47,Male,Black,false,NATURAL,COMPLICATIONS OF MORBID OBESITY,NaN,NaN,NaN,False,False,1132 TROOST AVENUE APT 101,FOREST PARK,-87.8169297,41.8653484,77748,"(41.8653484, -87.8169297)"
15,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37,Male,White,true,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,159TH AND FINCH,HARVEY,-87.6401039,41.6008977,58723,"(41.6008977, -87.6401039)"
16,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37,Male,White,false,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,False,true,6547 W. 111TH APT W-27,WORTH,-87.7817317,41.6896403,63784,"(41.6896403, -87.7817317)"
17,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31,Male,Black,false,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,False,False,6916 S. MICHIGAN AVENUE,CHICAGO,-87.6221153,41.7686918,77583,"(41.7686918, -87.6221153)"
18,ME2018-01130,02/17/2018 12:00:00 AM,03/02/2018 11:31:00 PM,66,Male,White,false,ACCIDENT,CLOSED HEAD INJURIES,NaN,NaN,CHRONIC ETHANOLISM,False,False,6238 w. 26th #205,BERWYN,-87.7800927,41.8432672,57453,"(41.8432672, -87.7800927)"
19,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
20,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31,Male,Black,false,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,true,False,4811 W. WASHINGTON BLVD.,CHICAGO,-87.7456512,41.8817674,77825,"(41.8817674, -87.7456512)"
21,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69,Male,White,false,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,False,False,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
22,ME2018-02125,05/01/2018 01:00:00 PM,05/03/2018 01:52:00 PM,49,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1653 W Congress Pkwy,NaN,-87.6679448,41.8751081,78013,"(41.8751081, -87.6679448)"
23,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37,Male,Black,false,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,False,False,1440 EMBASSY LANE,FORD HEIGHTS,-87.5852155,41.5133297,78840,"(41.5133297, -87.5852155)"
24,ME2014-00102,08/17/2014 12:00:00 PM,08/17/2014 03:11:00 PM,39,Female,Black,false,SUICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,"23443 WESTERN AVENUE, APT. 72",PARK FOREST,NaN,NaN,63896,NaN
25,ME2014-00339,09/02/2014 08:14:00 PM,09/03/2014 04:13:00 AM,54,Male,White,false,ACCIDENT,CEREBRAL INJURIES,NaN,NaN,NaN,False,False,IRVING PARK RD AT SALT CREEK,WOOD DALE,NaN,NaN,62191,NaN
26,ME2018-02136,05/03/2018 09:05:00 PM,05/03/2018 09:47:00 PM,53,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"8301 SOUTH 88TH AVE, APT 412",JUSTICE,NaN,NaN,77854,NaN
27,ME2018-02166,04/30/2018 03:00:00 PM,05/06/2018 06:09:00 AM,66,Male,White,false,NaN,NaN,NaN,NaN,NaN,False,False,1815 N. KARLOV,CHICAGO,-87.7286374,41.9140656,77857,"(41.9140656, -87.7286374)"
28,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48,Male,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,OBESITY,False,False,2631 West Rascher Avenue,CHICAGO,-87.6954789,41.9802154,77843,"(41.9802154, -87.6954789)"
29,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76,Male,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS AND OBESITY,False,False,8108 ODELL AVENUE,BRIDGEVIEW,-87.8036075,41.7440145,77849,"(41.7440145, -87.8036075)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22605,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50,Male,White,true,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",False,False,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.6967797,41.8521269,70244,"(41.8521269, -87.6967797)"
22606,ME2018-02089,05/01/2018 08:16:00 PM,01/01/1970 12:00:00 AM,NaN,NaN,NaN,false,NaN,NON-HUMAN REMAINS,NaN,NaN,NaN,False,False,729 E OAKWOOD BLVD,CHICAGO,-87.608927,41.8226731,75628,"(41.8226731, -87.608927)"
22607,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48,Female,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC KIDNEY DISEASE,False,False,201 W. 69TH STREET,CHICAGO,-87.6302482,41.768766,72642,"(41.768766, -87.6302482)"
22608,ME2018-02092,05/01/2018 10:30:00 PM,05/01/2018 10:38:00 PM,48,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,7846 S Kingston,CHICAGO,-87.5626855,41.7522303,77795,"(41.7522303, -87.5626855)"
22609,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.6228345,41.8417184,77971,"(41.8417184, -87.6228345)"
22610,ME2018-02099,05/02/2018 09:45:00 AM,05/02/2018 09:49:00 AM,30,Male,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,250 N. Western Avenue,NaN,-87.6869702,41.8860494,77976,"(41.8860494, -87.6869702)"
22611,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56,Male,Black,false,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,False,False,216 w. 147TH STREET,HARVEY,-87.6689548,41.6224931,78086,"(41.6224931, -87.6689548)"
22612,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55,Female,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,False,False,1755 HENLEY ST #2N,GLENVIEW,-87.8022124,42.0700695,78280,"(42.0700695, -87.8022124)"
22613,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.8624014,78381,"(41.8624014, -87.640188)"
22614,ME2018-02094,05/01/2018 09:10:00 PM,05/01/2018 10:12:00 PM,54,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9858 IRVING PARK ROAD,SCHILLER PARK,-87.8733682,41.9561261,78475,"(41.9561261, -87.8733682)"
22615,ME2018-02097,05/02/2018 06:00:00 AM,05/02/2018 06:49:00 AM,53,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,2373 E 70TH ST,CHICAGO,-87.5672724,41.768022,78635,"(41.768022, -87.5672724)"
22616,ME2018-02101,05/02/2018 07:00:00 AM,05/02/2018 10:03:00 AM,43,Male,White,true,PENDING,PENDING,NaN,NaN,NaN,False,False,9558 SHERMER ROAD,MORTON GROVE,-87.8117716,42.0547758,77791,"(42.0547758, -87.8117716)"
22617,ME2018-02103,04/30/2018 12:00:00 AM,05/02/2018 01:21:00 PM,77,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,"1001 Elm Street, South West",DEMOTTE,NaN,NaN,57915,NaN
22618,ME2018-02109,05/02/2018 05:00:00 PM,05/02/2018 05:18:00 PM,59,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,529 RIDGEWOOD ROAD,ELK GROVE VILLAGE,-87.982034,42.0181695,77811,"(42.0181695, -87.982034)"
22619,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.6570785,41.7267165,77789,"(41.7267165, -87.6570785)"
22620,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91,Male,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2058 W. Hutchinson,CHICAGO,-87.6812383,41.9589732,67932,"(41.9589732, -87.6812383)"
22621,ME2018-02116,04/21/2018 10:00:00 PM,05/03/2018 12:15:00 PM,88,Male,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,7140 S. MARSHFIELD AVENUE,CHICAGO,-87.6652684,41.7637034,59566,"(41.7637034, -87.6652684)"
22622,ME2018-02118,05/03/2018 08:00:00 AM,05/03/2018 09:57:00 AM,29,Female,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9000 West College Park way,PALOS HILLS,-87.837735,41.6895094,77788,"(41.6895094, -87.837735)"
22623,ME2018-02124,05/03/2018 03:09:00 PM,05/03/2018 11:33:00 AM,60,Female,Black,false,NaN,NaN,NaN,NaN,NaN,False,False,8419 S ESCANABA AVE,NaN,-87.5536891,41.7422211,67087,"(41.7422211, -87.5536891)"
22624,ME2018-02126,05/03/2018 02:01:00 PM,05/03/2018 02:37:00 PM,61,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,1512 SILVER LANE APT #1,PALATINE,-88.0073415,42.1364923,77779,"(42.1364923, -88.0073415)"
22625,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1127 Miller Lane;,BUFFALO GROVE,-87.9784066,42.1347284,77891,"(42.1347284, -87.9784066)"
22626,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73,Male,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.6438762,41.9419529,77939,"(41.9419529, -87.6438762)"
22627,ME2018-02115,05/03/2018 08:32:00 AM,05/03/2018 08:52:00 AM,0,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,16102 RICHMOND AVE,MARKHAM,-87.687286,41.5972276,78018,"(41.5972276, -87.687286)"
22628,ME2018-02120,05/03/2018 11:00:00 AM,05/03/2018 12:18:00 PM,32,Female,Black,false,PENDING,PENDING,NaN,NaN,NaN,False,False,9158 S. HARVARD AVENUE,CHICAGO,-87.6321484,41.7277694,77985,"(41.7277694, -87.6321484)"
22629,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42,Male,Black,false,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,true,False,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.5839097,41.7464877,78103,"(41.7464877, -87.5839097)"
22630,ME2018-02104,12/31/2017 11:23:00 PM,05/02/2018 01:59:00 PM,34,Male,White,false,PENDING,PENDING,NaN,NaN,NaN,False,False,5535 NORTH LINCOLN AVENUE,CHICAGO,-87.6934761,41.9824976,78129,"(41.9824976, -87.6934761)"
22631,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94,Male,White,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",False,False,16416 EVANS AVENUE,SOUTH HOLLAND,-87.6009945,41.5966344,78272,"(41.5966344, -87.6009945)"
22632,ME2018-02114,05/03/2018 08:09:00 AM,05/03/2018 08:19:00 AM,68,Male,Am. Indian,false,PENDING,PENDING,NaN,NaN,NaN,False,False,15243 3RD AVE.,PHOENIX,-87.6318491,41.6119409,78496,"(41.6119409, -87.6318491)"
22633,ME2018-02105,05/02/2018 02:00:00 PM,05/02/2018 02:25:00 PM,50,Male,White,false,SUICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,true,False,640 CUMBERLAND ST,HOFFMAN ESTATES,-88.07934,42.0394902,78745,"(42.0394902, -88.07934)"
22634,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57,Male,Black,false,NATURAL,CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,False,False,3914 212 PL,MATTESON,-87.7114567,41.5041136,78828,"(41.5041136, -87.7114567)"

### Check the top 5 primary causes. Cardiovascular disease should be first with about 28.4%

In [64]:
df[df["Primary_Cause"].str.contains("CARDIOVASCULAR").fillna(False)].shape

(6449, 20)

We could also clean up gunshots, but... let's just move on.

# The Opioid Epidemic

America has a [big problem with fentanyl](https://www.theatlantic.com/health/archive/2018/05/americas-opioid-crisis-is-now-a-fentanyl-crisis/559445/) and other opioids.

## Find all of the rows where fentanyl was part of the primary cause of death

We don't need `na=False` any more because we *dropped the rows without primary causes*.

In [154]:
df[df["Primary_Cause"].str.contains("FENTANYL").fillna(False)]["Primary_Cause"]

16       COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...
54       ETHANOL AND COMBINED DRUG (PROBABLE HEROIN, CY...
55          COMBINED FENTANYL AND PROBABLE HEROIN TOXICITY
70               FENTANYL, HEROIN, AND ALPRAZOLAM TOXICITY
94                           COCAINE AND FENTANYL TOXICITY
100         COCAINE, FENTANYL AND ACETYL FENTANYL TOXICITY
103      COMBINED DRUG (FENTANYL, METHADONE, AND ALPRAZ...
107        COMBINED DRUG (FENTANYL AND METHADONE) TOXICITY
108                          FENTANYL AND COCAINE TOXICITY
110      COMBINED DRUG (HEROIN, FENTANYL, AND ACETYL FE...
176                  COMBINED HEROIN AND FENTANYL TOXICITY
194                  FENTANYL AND ACETYL FENTANYL TOXICITY
233      COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TO...
256      FENTANYL, DIAZEPAM, LORAZEPAM, AND SERTRALINE ...
389                       FENTANYL AND ALPRAZOLAM TOXICITY
397      COMBINED DRUG (CARFENTANIL, FURANYL FENTANYL, ...
430      COMBINED DRUG (2-FURANYLFENTANYL, CYCLOPROPYL ...
463                COMBINED FENTANYL AND DIAZEPAM TOXICITY
471      COMBINED DRUG TOXICITY (FENTANYL, ACETYL FENTA...
475      COMBINED DRUG (COCAINE, HEROIN AND FENTANYL) T...
507      COMBINED DRUG (ACETYL FENTANYL AND FENTANYL) T...
540      METHOXYACETYL FENTANYL, CYCLOPROPYL FENTANYL H...
541      COMBINED DRUG (FENTANYL, HEROIN, ETHANOL) TOXI...
573      COMBINED DRUG TOXICTY (ACETYL FENTANYL, FENTAN...
584         ALCOHOL, COCAINE, HEROIN AND FENTANYL TOXICITY
595      COMBINED DRUG TOXICITY (FENTANYL, ACETYL FENTA...
679      COMBINED DRUG (HEROIN, FENTANYL, AND ACETYL FE...
680      COMBINED DRUG (CYCLOPROPYL FENTANYL, ACRYL FEN...
688                  COCAINE, HEROIN AND FENTANYL TOXICITY
786      COMBINED DRUG TOXICITY (FENTANYL, ACETYL FENTA...
                               ...
22231    COMBINED DRUG TOXICITY (FENTANYL, FURANYL FENT...
22255    COMBINED HEROIN, FENTANYL, ACRYL FENTANYL, AND...
22279    COMBINED FURANYL FENTANYL, 4-ANPP (DESPROPIONY...
22290    COMBINED FENTANYL, MITRAGYNINE, AND DIAZEPAM I...
22292                        FENTANYL AND ETHANOL TOXICITY
22294    COMBINED DRUG (PHENOBARBITAL, LORAZEPAM, ALPRA...
22311    COMBINED ETHANOL AND DRUG (DESPROPIONYL FENTAN...
22312    COMBINED DRUG (HEROIN, FENTANYL, COCAINE) TOXI...
22321    COMBINED DRUG (FENTANYL AND AMITRIPTYLINE) TOX...
22348    COMBINED DRUG (COCAINE, OPIATE, AND FENTANYL) ...
22350    MIXED DRUG INTOXICATION (MORPHINE, FENTANYL, C...
22353    COMBINED DRUG (PSEUDOEPHEDRINE, ALPRAZOLAM, HY...
22372    COMBINED FENTANYL, ACETYL FENTANYL AND ETHANOL...
22375    COMBINED DRUG (FENTANYL, ACETYL FENTANYL, COCA...
22378    COMBINED DRUG (DESPROPRIONYL FENTANYL(4-ANPP) ...
22386           COCAINE, FENTANYL, AND HEROIN INTOXICATION
22391    COMBINED DRUG (HEROIN, FENTANYL, ACETYL FENTAN...
22394    COMBINED DRUG TOXICITY (ACRYL FENTANYL, DESPRO...
22409    COMBINED DRUG TOXICITY (HEROIN, METHOXYACETYL ...
22410            COMBINED DRUG TOXICITY (HEROIN, FENTANYL)
22414    COMBINED DRUG (FENTANYL AND PROBABLE HEROIN) T...
22418       HEROIN, FENTANYL, AND ACETYL FENTANYL TOXICITY
22446    COMBINED DRUG (HEROIN AND CYCLOPROPYL FENTANYL...
22460    COMBINED CYCLOPROPYL FENTANYL AND ETHANOL TOXI...
22461                                    FENTANYL TOXICITY
22483         COMBINED DRUG (HEROIN AND FENTANYL) TOXICITY
22484    COMBINED DRUG (FENTANYL AND ACETYL FENTANYL) T...
22488                                    FENTANYL TOXICITY
22503    COCAINE, METHADONE, HEROIN, FENTANYL AND ACETY...
22550    COMBINED DRUG (FENTANYL, CYCLOPROPYLFENTANYL, ...
Name: Primary_Cause, Length: 1493, dtype: object

## Fentanyl and race

In the late 80's and 90's, the [crack cocaine epidemic](https://en.wikipedia.org/wiki/Crack_epidemic) swept through inner cities in the US. It was treated primarily as a crime problem, while many people say fentanyl and heroin overdoses are being treated as a medical problem due to the racial differences - the crack epidemic mainly affected Black communities, while fentanyl seems to be a problem for everyone.

### How does the racial breakdown of fentanyl deaths compare to the racial breakdown of other causes of death? How about compared to causes of accidental death?

In [224]:
df[df["Primary_Cause"].str.contains("FENTANYL").fillna(False)].Race.value_counts(normalize=True) * 100

White         55.592766
Black         43.536504
Asian          0.401875
Other          0.334896
Unknown        0.066979
Am. Indian     0.066979
Name: Race, dtype: float64

In [225]:
df[df["Manner_of_Death"]== "ACCIDENT"].Race.value_counts(normalize=True) * 100

White         64.141282
Black         32.930672
Other          1.391807
Asian          1.352416
Unknown        0.091912
Am. Indian     0.091912
Name: Race, dtype: float64

### Now compare it to homicides

In [226]:
df[df["Manner_of_Death"]== "HOMICIDE"].Race.value_counts(normalize=True) * 100

Black      77.425044
White      21.199295
Other       1.164021
Asian       0.176367
Unknown     0.035273
Name: Race, dtype: float64

### Now compare it to suicide

In [227]:
df[df["Manner_of_Death"]== "SUICIDE"].Race.value_counts(normalize=True) * 100

White      79.836353
Black      15.371128
Asian       3.506721
Other       1.227352
Unknown     0.058445
Name: Race, dtype: float64

## These differences seems kind of crazy

Let's look at all of these at once: I want a breakdown of the most common manners of death for **men**, based on race.

Percentages, please, not raw numbers.

You can look at women, too, although I think the numbers are more surprising for men.

In [231]:
df[df["Gender"]== "Male"].Race.value_counts(normalize=True) * 100

White         54.974600
Black         42.157106
Asian          1.424854
Other          1.294759
Unknown        0.086730
Am. Indian     0.061950
Name: Race, dtype: float64

## Back to drugs: what is the most popular opioid-related primary cause of death that does NOT involve fentanyl?

- *Tip: Pay attention to your column names! There's one that might tell you if something is opioid-related...*
- *Tip: Usually you can use `not` or `!` to means "not", but for pandas and `.isin` or `.str.contains` you need to use `~`*
- *Tip: For "and" in pandas you'll need to use `&`, and make sure all of your clauses have parens around them, e.g. `df[(df.col1 = 'A') & (df.col2 = 'B')]`.*

# How do heroin and fentanyl deaths compare?

## Count the number of deaths involving heroin, the number of deaths involving fentanyl, and the number of deaths involving both.

- *Tip: This will take 3 different statements*
- *Tip: You should get `813` that include both*

In [234]:
df[df["Primary_Cause"].str.contains("FENTANYL").fillna(False)].Primary_Cause.count()

1493

In [238]:
df[df["Primary_Cause"].str.contains("HEROIN").fillna(False)].Primary_Cause.count()

2022

In [265]:
df[df["Primary_Cause"].isin(["HEROIN","FENTANYL"]).fillna(False)].Primary_Cause.count()

0

## That's weird.

I heard fentanyl really surpassed heroin in the past few years. Let's see how this 

### Pull the year out and store it in a new column called `year`

If you run `df['Date of Incident'].str.extract("(\d\d\d\d)", expand=False)`, it will pull out the year of each incident. **Store this in a new column called `year`.**

(It's regular expression stuff. `\d\d\d\d` means "four numbers in a row", and `()` + `.str.extract` means "pull it out".)

In [269]:
df["year"] = df['Date_of_Incident'].str.extract("(\d\d\d\d)", expand=False)

### What is the datatype of the new `year` column?

In [276]:
df["year"].dtype

dtype('O')

## Convert this new column to an integer and save it back on top of itself

- *Tip: This uses is your friend `.astype`*
- *Tip: Make sure to save it back on top of itself!*

In [310]:
#df["year"] = 
df["year"].isnull().value_counts()
df["year"] = df["year"].fillna(False)
df["year"] = df["year"].astype(int)

## Confirm the column is a number

In [311]:
df["year"].dtype

dtype('int64')

## Plot the number of opioid deaths by year

If you'd like to make it look nicer, do some sorting and get rid of 2018.

- *Tip: Think of it in a few steps. First, filter for opioid deaths. Then get the number of deaths for each year. Then plot it.*
- *Tip: What's up with 2018? Why's it look so weird? Can you get rid of it? Remember to use lots of parens!*
- *Tip: Make sure the earliest year is on the left. You might need to sort by something other than values.*

AttributeError: 'Series' object has no attribute 'Opioid_Related'

## Plot the number of fentanyl deaths by year, and the number of heroin deaths by year

- *Tip: You'll want to look up how to use `ylim` - it will let you set each graphic to use the same scale. This should be separate graphics.*
- *Tip: Pay attention to the numbers on your axes. `sort_index()` will be your friend.*
- *Tip: You should probably get rid of 2018*

In [337]:
df[df["Primary_Cause"].str.contains("HEROIN").fillna(False)].Primary_Cause.plot()

TypeError: Empty 'DataFrame': no numeric data to plot

In [338]:
df[df["Primary_Cause"].str.contains("FENTANYL").fillna(False)].Primary_Cause.plot()

TypeError: Empty 'DataFrame': no numeric data to plot

## How does this compare to gun deaths?

## But hey: numbers can lie pretty easily!

The numbers are just so low in 2014 and much higher in 2017. What's going on there?

Well, maybe **there just isn't as much data from the earlier years**. Plot how many entries there are for each year.

And we don't know the best way to fix that up yet, so instead I'm going to give you a present.

# Is the true lesson here, don't move to Cook County, Illinois?

Cook County is basically Chicago. It's probably just certain areas that are trouble, right? Let's investigate that without even having a clue how mapping works.

## Fun bonus: Making cheating maps

### Make a new dataframe of every death in the actual city of Chicago

### Confirm this new dataframe has 13,627 rows

### Use lat and long in the worst way possible to make a map

Use `longitude` and `latitude` and `plot` to make a rough map of the city. Chicago [looks like this](https://en.wikipedia.org/wiki/File:DuPage_County_Illinois_Incorporated_and_Unincorporated_areas_Chicago_Highlighted.svg)

- *Tip: Use the `latitude` and `longitude` columns*
- *Tip: You don't want a line graph, of course. Or a bar. What kind is the kind with dots on it?*
- *Tip: Use something like like `figsize=(10,5)` to specify the height and width of the map (but, you know, with better numbers that make it look like chicago)*

## Now let's find out where to live

Make a map of every non-homicide death in Chicago, then plot the homicides on top of it.

Use the `ax=df.plot` trick from the beer cans assignment to plot all of the rows representing homicides vs non-homicides. You can use `color='red'` to make one of them red, and `alpha=0.05` to make each mark very transparent to allow them to layer on top of each other.

## Never tell anyone I let you do that.

But you want to see something actually completely legitimately insane?

**Chicago is one of the most segregated cities in America.** If you'd like to see this for yourself, make a map of `Race`. Plot black vs white in a way similar to what we did above.

Yup.